\documentclass[11pt,a4paper]{article}
\usepackage[top=1.00in, bottom=1.0in, left=1.1in, right=1.1in]{geometry}
\usepackage{graphicx}
\usepackage[sort&compress]{natbib}
%\bibliographystyle{..//..//bib/styles/gcb}
\usepackage{Sweave}
\usepackage{xcolor}

\usepackage[hyphens]{url}
\usepackage{caption}
\usepackage{subcaption}

\setlength\parindent{0pt}
\usepackage{xr}

\usepackage{lineno}
%\usepackage{xr-hyper}
\externaldocument{phenoNAmPhylo}
\externaldocument{phenoNAmPhyloSM}

\newcommand{\lr}[1]{line~\lineref{#1}}

%\lr{refline1}

\begin{document}
\SweaveOpts{concordance=TRUE}

\renewcommand{\bibname}{References}%names reference list 

Reviewer comments are italicized and our detailed explanation of changes are in regular text. \\

\textbf{Reviewer 1 Comments to the Author:}\\

\emph{Deirdre Loughnan and Elizabeth Wolkovich have elegantly integrated experimental twig phenology work and sophisticated modeling in their manuscript “How temperature, photoperiod and evolutionary history shape forest leaf out.” The manuscript is well written and well organized, with sound connections to ecological theory and intentional tests of the well-known environmental cues, temperature and photoperiod, driving shifts in leaf out phenology. This concise work upgrades our understanding of population-, species-, and community-level phenology and clarifies fruitful research directions for ecological forecasting. This is perhaps the most polished twig-cutting common garden experiment that I’ve read and Wolkovich continues to “model” how to write methods for Bayesian models in clean, clear sentences.} \\

We thank the reviewer for this positive feedback and are glad to hear they found our manuscript to be well written and theoretically sound. \\

\emph{I am reasonably confident that readers familiar with phenology will clearly understand the difference between “response” as a rate in phenological shift per cue and “timing” as a date, but I do wonder if Ecology readers in general will immediately grasp this subtly throughout the paper.}\\

We appreciate the reviewers insight and agree that a more detailed explanation of these terms would improve the clarity of our work for a wider readership. We have clarified this point in the abstract from \lr{R1_respTime1} to \lr{R1_respTime1b}, in the methods from \lr{R1_respTime2} to \lr{R1_respTime2b}, in the results from \lr{R1_respTime3} to \lr{R1_respTime3b}, and in the captions of Figures 3 \& 4. \\

\emph{My only other manuscript-level concern is merely the peccadillo that the authors gloss over the experimental design(s) which incorporates both twig cuttings and a common garden element in that the twigs from two provenances/populations experience phenological forcing (under various photoperiod and temperature treatments) together. As an experimental ecologist, I would appreciate a slightly firmer grounding in the common garden and twig forcing methods and literature, though that may be my own professional bias. I have included my line edits below. I look forward to seeing this paper in the pages of Ecology! Kudos to the authors.}\\

We see the reviewers point and have added additional discussion of twig experiments and common garden studies from \lr{R1_commG} to \lr{R1_commGb}. We have also added details of our study design to the methods on \lr{R1_thermoP}.\\

% "elegantly integrated experimental twig phenology " and our statistical approach as "sophisticated"
% Appreciate that the reviewer finds our manuscript to be "well written and well organized"

\emph{Title: I think you need an Oxford comma after “photoperiod”}\\

Done.\\

\textbf{Abstract:}\\

\emph{Line 2: I dislike how you open with a passive verb. “Has received growing attention” from whom?}\\

We see the reviewers point and have revised this sentence to no longer include this passive verb. This sentence now reads (\lr{R1_1}):

\begin{quote}
Climate change has shifted the timing of major life cycle events across most systems. These shifts may in turn alter how species assemble temporally.
\end{quote}

\emph{Line 6: I think you should add “twig” before “budburst” to note that this is a twig study.}\\

We have revised this sentence to clarify that we are measuring budburst of cuttings from woody plants on \lr{R1_2}.\\

\emph{Line 12: I bumped on the phrase “intrinsic species differences in timing.” I think you mean that some species are just earlier than others, like maples are just leafing out before oaks, but I wonder if I misinterpreted this.}\\

The reviewer is correct in their interpretation, but we appreciate how this could be more explicit. We have revised this sentence from \lr{R1_instrinPhylo} to \lr{R1_instrinPhylob} for clarity. \\

\emph{Line 13: Is “shared evolutionary history” implying something broader than phylogenetic relationships? Asking because “temperature and photoperiod cues” are noted as model variables in line 7 and then this language is repeated as “temperature and photoperiod cures” in the results in line 11, but “phylogenetic Bayesian model” becomes “shared evolutionary history” when reported as a result.}\\

We appreciate the importance of word choice and agree with the reviewer that a different word would be more accurate. We have revised this sentence as follows (\lr{R1_instrinPhylo} to \lr{R1_instrinPhylob}):\\
\begin{quote}
Differences in species responses to well-studied temperature and photoperiod cues explained only half of the observed variation in leafout date, with the remaining variation explained in part by the estimated phylogenetic structure of leafout, representing species shared evolutionary history
\end{quote}

\textbf{Introduction}\\

\emph{Line 35: surprised to see that Heberling, J. Mason, Caitlin McDonough MacKenzie, Jason D. Fridley, Susan Kalisz, and Richard B. Primack. "Phenological mismatch with trees reduces wildflower carbon budgets." Ecology letters 22, no. 4 (2019): 616-623 was NOT the Heberling et al 2019 that you cited here. In addition to the invasion story in your Heberling, this other Heberling links understory-overstory asynchrony with carbon budgets which is also relevant to lines 39-42. (and wow Heberling had a productive 2019!)}\\

We appreciate the reviewer suggesting this interesting and relevant work, we have added this citation on \lr{R1_Heberling1}.\\

\emph{Lines 57-58: Here, you touch on inter- and intraspecific variation in phenological response, but then shift the focus entirely to interspecific variation and the cues that structure this variation and theory that predicts it for the rest of the paragraph. Why not give the same treatment to intraspecific variation — especially since your experimental design explores populations from two different sites on each coast? What is the theoretical explanation for intraspecific variation in phenological response and why would understanding the cues that structure this variation be important for ecological forecasting?}\\

We see the reviewers point and have revised our introduction from \lr{R1_intraSp} to \lr{R1_intraSpb} to include a discussion of intraspecific variation in phenological responses and their importance to ecological forecasting.\\

\textbf{Methods:}\\

\emph{Lines 91-106: I’m impressed with the experimental design for this twig study since I was raised in a lab that completed similar work in dunkin donuts cups located in the back of a teaching lab (McDonough MacKenzie, Caitlin, Amanda S. Gallinat, and Lucy Zipf. 2020. Low-cost observations and experiments return a high value in plant phenology research. Applications in Plant Sciences.) Although, I did miss the citation for Primack, Richard B., Julia Laube, Amanda S. Gallinat, and Annette Menzel. "From observations to experiments in phenology research: investigating climate change impacts on trees and shrubs using dormant twigs." Annals of botany 116, no. 6 (2015): 889-897.}\\

We thank the reviewer for this positive comment and for sharing these interesting references, we have revised our references on \lr{R1_Primack}. \\

\emph{Line 186: please define “thermoperiodicity”}\\

Done (\lr{R1_thermoP}).\\

\textbf{Results:}\\

\emph{Line 193-195: Move “after the start of forcing and photoperiod treatments” to immediately follow “30.4 days”; complete the sense before the parentheses.}\\

Done (\lr{R1_Results}).\\

\emph{Lines 247-251: How do you determine whether community-level eastern v western budburst date differences are due to different species in these communities versus different collection dates? And is this a meaningful comparison given the different species pools? I guess I just assumed the meaningful site comparisons were North and South within each set of twig cutting experiments, since this would test the intraspecific variation in response.}\\

We can see how this statement was confusing and requires greater clarification. We have carefully reviewed and updated the text to consistently use site, community and transect throughout the manuscript (such as on \lr{R1_site1}, \lr{R1_site2}, \lr{R1_site3}, and \lr{R1_site4}). We are able to attribute differences in budburst site-level differences and not collection dates by using in our model the total chill portions for each individual site, which includes both the field chilling experienced prior to sampling (calculated using site-specific weather data) and experimental chilling (\lr{R1_collect} to \lr{R1_collectb}). We believe that this is a meaningful comparison, as we sampled many species in the same clades in each transect, and thus we would expect more closely related species to be similar in their phenology and responses to cues regardless of their site of origin, which we believe further highlights the importance of including the phylogenetic structure in our analysis. \\  

\textbf{Discussion}\\

\emph{Line 272:When you write “we found no detectable site-level differences” I wondered if you meant at the community level or at the species level. Again, I am confused by the coastal comparisons because I expect that the differences in community composition would swamp this comparison.}\\ 

We were equally surprised to find that the differences in community composition did not swamp the differences across sites and, as we discussed above have made changes throughout to make our results and interpretation of this clearer. We have revised this sentence starting on \lr{R1_swamp} to now read:

\begin{quote}
Despite the high degree of diversity and spatial scale represented in our study, we found no detectable differences in the responses to temperature and photoperiod at our different sites, even though sites span different coasts and over 6$^{\circ}$ of latitude.
\end{quote}

\emph{Lines 271-276: What about common garden studies? In McDonough MacKenzie et al 2019, Vitasse et al 2013, Stinson 2005, and
Vitasse et al 2010 local condition drove phenology, while Korner et al 2015, Gugger et al 2015, Vitasse et al 2009, and Rossi and Isabel 2016 reported population-level variation in phenological response.}\\

We agree that this is an important topic that requires more detail, we have therefore revised this section of the discussion from \lr{R1_commG} to \lr{R1_commGb}.\\

\emph{Lines 295-297: I recommend adding Polgar, Caroline, Amanda Gallinat, and Richard B. Primack. "Drivers of leaf‐out phenology and their implications for species invasions: insights from Thoreau's Concord." New Phytologist 202, no. 1 (2014) to this section.}\\

Done (\lr{R1_Polgar}).\\

\emph{Lines 300-302: As in Line 35, I think Herbeling et al 2019’s overstory-understory asynchrony paper belongs here}\\

Done (\lr{R1_Herb2}). \\

\emph{Line 312: the discussion “latent traits” reminds me of Inouye’s conceptual synthesis on phenology as a process and a trait (Inouye, Brian D., Johan Ehrlén, and Nora Underwood. "Phenology as a process rather than an event: from individual reaction norms to community metrics." Ecological Monographs 89, no. 2 (2019): e01352.)}\\

This is a great suggestion, we now include this reference on \lr{R1_inouye}.\\

\emph{Lines 330-331: I was surprised by the statement that species in northern communities were most likely to “experience the greatest changes in budburst order” as I did not make that connection while reading your results. Can you provide more context here or point the reader to a specific figure?}\\

We see how more clarity and context is needed in discussing this result. This statement was in reference to our results on \lr{R1_rankOrder}, which suggest that the order with which species budburst depends on the strength of the cues. We have revised this sentence from \lr{R1_rank} to \lr{R1_rankb} to provide more context and have a more explicit link to our results.\\

\emph{Lines 336-338: This sentence implies that the reader already agrees that forecasting phenology is meaningful and important, but authors never explicitly state why phenological forecasting is ecologically relevant for management, conservation, theory, or practice. Why does forecasting matter? And why does it need to be improved?}\\

We see the reviewers point and have revised this section of our discussion substantially from \lr{R1_2_Discuss} to \lr{R1_2_Discussb} to explicitly state why phenological forecasting is important and why it needs to be improved.\\

\textbf{Figures 1:}\\

\emph{I think the species lists should be moved to their own table to simplify the conceptual design of this figure.}\\

We agree that removing the species list would simplify the figure and have now removed it, instead referencing in the figure caption the list of species in Table S1 .\\

\textbf{Reviewer 2 Comments to the Author:}\\

\emph{This study examined how temperature, photoperiod, and evolutionary history shape tree leaf-out across 47 woody species in North America using manipulative experiments and phylogenetic Bayesian modeling. The results reveal that species-specific responses to chilling, forcing, and photoperiod cues explain only about half of the variation in budburst timing, with the remaining variation attributed to intrinsic species differences and shared evolutionary history. These findings provide important insights into phenological forecasting and community assembly. However, several issues need to be addressed before publication.}\\

We are glad that the reviewer found the insights from our work to be an important contribution to the field.\\

\emph{First, the quantification and interpretation of the intercept require further clarification. The authors should provide additional methodological details explaining how the species-level intercepts ($\alpha_{spi}$) represent timing differences independent of the manipulated cues.}\\

We see the reviewers point and have revised this sentence starting on \lr{R2_intercept} of our methods to improve clarity. As we are using z-scored values in our model, the intercepts for each species represent the species-level day of budburst realtive to the mean day of budburst when when all cue and site predictors are at their mean values \citep{GelmanROS}.\\

\emph{In addition, while the authors attribute the unexplained variation to shared evolutionary history, the intercept may potentially contain confounding effects from other factors beyond phylogeny. It would therefore be helpful to test whether phylogenetic distance is related to leaf-out timing (or to the residuals of the model based on chilling, forcing, and photoperiod), which would provide more direct support for the phylogenetic interpretation.}\\

This is a good point, and we agree that the intercept could contain additional effects from other factors besides phylogeny. To check this, we performed an additional analysis using a model in which the phylogenetic structure was placed on the residuals instead of the intercept. This revised model produced similar estimates  ($\lambda$: 0.49) of the phylogenetic structure as our main model ($\lambda$: 0.43), confirming that species-level variation not explained by the cues does seem attributable in part to evolutionary history. The discussion of this analysis can be found on \lr{R2_resid} of the methods and \lr{R2_residResult} of the results section, in additional to a new table in the supplementary material (Table S2). \\

\emph{Furthermore, the Discussion focuses primarily on mechanistic explanations. It would be valuable to expand this section to address the broader implications of the findings and to more clearly emphasize the significance of the study’s contributions for phenological prediction and community-level responses to climate change.}\\

We completely agree with the reviewer and have added a more detailed discussion of the implications of our findings and their contribution to phenological prediction and community-level responses to climate change from \lr{R1_2_Discuss} to \lr{R1_2_Discussb}.\\

\emph{Finally, the presentation of the figures requires improvement. In Fig. 2, numerical intercept values for each species could be added, and the annotation of phylogenetic relationships among major clades should be improved to enhance interpretability.}\\

We appreciate the reviewer's suggestions to improve the interpretability of the phylogenetic relationships. We have added the numerical intercept values to the tips of the phylogeny. We have also added additional annotation to denote the major clades represented in the tree. \\ 

\emph{In Figs. 4 and 5, the font sizes of axis labels, legends, and species names are currently too small to read comfortably. The presentation of species names on the x-axis should be standardized and clearly positioned below the axis for readability.}\\

We agree and have revised these two figures to now have larger axis labels, legends, and species names. Given that species are ordered on the x-axis based on their estimated day of budburst, the species names often overlap when positioned below the axis. We have now standardized the presentation of the name so that tree species are labelled above the axis and shrub species are labelled below and all labels are spaced to ensure their readability. We updated our captions to explain this.  \\ 

\bibliographystyle{bibliography/bibstyles/ecology}% 
\bibliography{bibliography/phenoBCBib.bib}

\end{document}