\documentclass{article}

% required 
\usepackage[hyphens]{url} % this wraps my URL versus letting it spill across the page, a bad habit LaTeX has

\usepackage{Sweave}
\usepackage{graphicx}
\usepackage{natbib}
\usepackage{amsmath}
\usepackage{textcomp}%amoung other things, it allows degrees C to be added
\usepackage{float}
\usepackage[utf8]{inputenc} % allow funny letters in citaions 
\usepackage[nottoc]{tocbibind} %should add Refences to the table of contents?
\usepackage{amsmath} % making nice equations 
\usepackage{listings} % add in stan code
\usepackage{xcolor}
\usepackage{capt-of}%alows me to set a caption for code in appendix 
\usepackage[export]{adjustbox} % adding a box around a map
\usepackage{lineno}
\linenumbers
% recommended! Uncomment the below line and change the path for your computer!
% \SweaveOpts{prefix.string=/Users/Lizzie/Documents/git/teaching/demoSweave/Fig.s/demoFig, eps=FALSE} 
%put your Fig.s in one place! Also, note that here 'Fig.s' is the folder and 'demoFig' is what each 
% Fig. produced will be titled plus its number or label (e.g., demoFig-nqpbetter.pdf')
% make your captioning look better
\usepackage[small]{caption}

\usepackage{xr-hyper} %refer to Fig.s in another document
\usepackage{hyperref}

\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{0pt}
\setlength{\belowcaptionskip}{10pt}

% optional: muck with spacing
\topmargin -1.5cm        
\oddsidemargin 0.5cm   
\evensidemargin 0.5cm  % same as oddsidemargin but for left-hand pages
\textwidth 15.59cm
\textheight 21.94cm 
% \renewcommand{\baselinestretch}{1.5} % 1.5 lines between lines
\parindent 0pt		  % sets leading space for paragraphs
% optional: cute, fancy headers
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead[LO]{Draft summer 2023}
\fancyhead[RO]{Temporal Ecology Lab}
% more optionals! %

\graphicspath{ {./figures/} }% tell latex where to find photos 
\externaldocument[supp-]{phenoNAmPhylo_SM}
\begin{document}
\renewcommand{\bibname}{References}%names reference list 

\SweaveOpts{concordance=TRUE} % For RStudio hiccups


\title{Differences in phenological cues responses do not explain temporal assembly of woody plant communities}
\date{\today}
\author{Deirdre Loughnan$^1$ and E M Wolkovich$^1$}
\maketitle 

$^1$ Department of Forest and Conservation, Faculty of Forestry, University of British Columbia, 2424 Main Mall
Vancouver, BC, Canada, V6T 1Z4. \\

Corresponding Author: Deirdre Loughnan, deirdre.loughnan@ubc.ca \\


\section*{Introduction}
<<label=runcode1,  echo=FALSE>>=

source("..//rcode/phenologyMsValues.R")
@

\begin{enumerate}
\item Plant phenology is changing with climate change:
\begin{enumerate}
\item Timing of spring bb is changing with anthropogenic climate change 
\item But changes are not uniform with some regions experiencing greater warming than others.
\item Responses are also  species specific and highly variable
\item Budburst in forest communities is the product of species differences as well as geographic variability in environmental cues.
\item Understanding the relative importance of these different drivers of budburst is needed to understand and predict future changes in spring phenology---and their ultimate impacts on growing season length, carbon cycle, species interactions
\end{enumerate}

\item Cues that shape bb
\begin{enumerate}
\item For woody plants, we do know there are three important environmental cues for bb:
\begin{enumerate}
\item Forcing: spring temperatures
\item Photoperiod/daylength
\item Chilling: winter length and temperatures
\end{enumerate}
\item But these cues interact---forcing can offset low chilling---photoperiod offsets weak forcing (Heide1993, Chuine2000, Caffarra2011, Flynn2018 )
\item The consistency and strength of these interactions across species and populations remains unclear.
\end{enumerate}

%DLAug28 --- edited the below to make it less broad
\item Cues can vary geographically and temporally---under future climates---likely to create differences in community dynamics and species composition.
\begin{enumerate}
\item Increasing winter and spring temperatures = faster accumulation of chilling and forcing (Guy2014)---associated with earlier budburst in many temperate plant species.
\item Could create novel niche space early in growing season---facilitating spp invasions or novel community assemblages
\item Will also reduce fitness in spp with strong photoperiod cues = limited in their ability to advance  (Korner2010) = different competitive landscape later in the growing season
\item Differences in species cue responses are likely to shape the diversity and persistence of species across forest communities.
\end{enumerate}
% \item Linking the effects of these cues and geography on species differences across pops = critical for predicting future impacts on forest community dynamics and species composition. 
% %DLAug19: is the above better?
% %emw3Jul -- this feels a little contradictory to 2c above ... as a reader I am not sure if I should care about population or species effects, but the beauty of your paper is you have both, so you just need to be nuanced in how you present them. I like the angle hinted at here of pulling them together with a forecasting focus as your paper's angle, especially as you're thinking about community assembly (so we care how species assemble, but they assemble in unique populations over space -- this is nice angle). 
% \begin{enumerate}
% \item Increasing winter and spring temperatures = faster accumulation of chilling and forcing \citep{Guy2014}
% \item Spp with strong photoperiod cues = limited in ability to advance (Korner2010)
% \item Could disrupt species interactions or alter niche space---facilitating spp invasions or novel community assemblages
% \item Knowing whether there are geographic trends in species responses will allow us to predict how local changes in climate will effect species fitness and ultimately persistence.
% \end{enumerate}


\item Variation in bb phenology across species in a community
\begin{enumerate}
%\item To date, most work has been devoted to understanding how environmental cues shape phenology and what drives the high species level variation in budburst
\item Timing of bb in a forest community can span several weeks---species fill different temporal niche
\item e.g. understory shrub spp tend to bb earlier than canopy species, likely reflecting overarching differences in growth strategies. 
\item But differences in budburst responses are likely to also exist across a species ranges---need to know the relative effects of pop vs sp
\end{enumerate}


\item While climate change may cause climates to shift rapidly, forest communities have assembled over longer timescales, with traits like phenology responding to local conditions. 
\begin{enumerate}
\item Across a species' spatial distribution---we can expect to see differences in both cues and therefore in spp responses in bb that have evolved over time
 \item Species with large latitudinal distributions experience differences in cues---e.g. photoperiod cues 
 %DLSept4: I am leaving the above bc I do feel like an illustrative example (ie photoperiod over latitudes) is needed, but we can cut it if need be
 % \item May also be experiencing different rates of temperature change over time---e.g. diff rates climate change across North America (Kunkel2004) %DLAug28: I could see this fitting in the discussion---cues are changing at diff rates---diff rates of change in forest communities btwn east and west
% \item Budburst across diff pop = result of local selective pressures---abiotic (local envirt) and biotic (competition and herbivory) %DLAug21: is introducing biotic factors too much here? Save it for trait paper?
\item But few studies have explored how cue use may differ across spatial gradient for the same forest communities and the role of local environments and biotic communities in shaping budburst across North America. 
\item To better predict how forest communities will respond and assemble under continued climate change we need to identify the cues that drive budburst in our dominant forest species and functional groups, and how these responses can change across populations. 
\end{enumerate}


% 
% \item Important to consider not just spp but communities as a whole---understand role phenology in shaping spp assemblages, community dynamics, and ecoystem services (Cleland2007).

\item In this study we:
\begin{enumerate}
\item Combined results from two growth chamber studies of woody plant phenological cues
\item Data from four populations, from eastern to western North America and a range of 4-6$^{\circ}$ latitude
\item Allows us to detect general trends in how bb of N Am. deciduous forest communities respond to forcing, chilling, photoperiod 
\item But also community specific responses---detect differences between Western and Eastern forest communities, and at different latitudes
\item And trends across different functional groups, exploring differences between the shrubs that dominate the forest understory and tree species.
%DLAug21: I decided to cut all mention of phylogeny from the intro and just discuss it in the methods.
%emw3Jul -- as you start working on intro I would adjust these -- the phylogeny should be sub-important and other questions should be first and more important I think; strong phylogenetic patterning is cool and important to consider in assembly, but that's not the BIG focus of your paper. 
\end{enumerate}
\end{enumerate}

\pagebreak

\section*{Discussion}

\begin{enumerate}
\item Our findings highlight the complex relationships between phenological cues and spring phenology within and across forest communities
\begin{enumerate}
\item In general, all species showed some cue response---earlier bb with stronger cue 
\item Chilling cues produced the strongest responses
\item Photoperiod produced the weakest cue response---consistent with previous studies
\item But strong chilling by forcing interaction---complex interactions between cues---eg Flynn2018, Heide1993, Caffarra2011
\item In taking a community approach---able to examine these relationships at the species level---where we find more complex patterns
\end{enumerate}

\item Within commnities, individual species differed in the timing of budburst and relative importance of cues (Fig. \ref{supp-fig:cueSp})  
\begin{enumerate}
\item Species differed substantially in their mean bb, with the average period of budburst in our eastern and western studies spanning \Sexpr{diffBBEast} and \Sexpr{diffBBWest} days respectively
\item This is similar to the period of budburst observed in natural communities---suggesting that our experiment captures a realistic breadth in phenology within our forest communities
\item While in general we found later budbursting species to have stronger chilling and forcing requirements, several of our earlier budbursting species did not have weaker cue responses that species that budburst later (Fig. \ref{cueGrad})
\item This suggests that budburst phenology is important part of a species temporal niche (Gotelli1996)---but may be shaped by other factors than temperature and light alone
\end{enumerate}

\item While shrub and tree species differ greatly in their ecological niche and physiology, this did not lead to clear differences in their budburst or cue responses.
\begin{enumerate}
\item We found no difference in cue responses between shrub or tree species for none of the three cues we tested.
\item This finding is surprising given previous studies have found earlier bb in shrubs compared to trees (Panchen2014, Yu2015) but is in line with Sun2006---who also found trees and shrubs to leaf out together
\item Currently prediction is that advances in tree species phenology will lead to reduced light and fitness for shrubs (Donnelly&Yu2019)---but if shrubs respond to changing cues similarly might keep pace with shifts in their canopy.
\end{enumerate}

\item We expected budburst across populations should be locally adapted in response to local selective pressures---but we found little evidence of poplation level differences
\begin{enumerate}
\item Our two eastern populations budburst slightly before our two western populations---strongest effect for chilling (Table 1)---could be due to differences in chilling requirements or the slightly greater chilling experienced in our eastern study
\item Across latitudes, our two eastern and two western populations do not differ (Fig \ref{siteCue}), which contrasts previous work that finds phenological events to occurr later in poleward populations (Zettlemoyer2021)
\end{enumerate}


\item phylogeny
\begin{enumerate}
\item Large portion of budburst due to spp differences - need more research to understand this, if not cues what causes it? Could introduce traits and foreshadow the third chapter  %emw1Jun2023 -- need to format results and discussion so this is a minor but important (and provocative/interesting) point 
\item The experimental design (which is impressive) combined with your models means that most other things some models would assign to the intercept are assigned to site, species, chill, force etc. here... and still the intercept is big. Wow!! 
\item Suggests factors other than species cues and architectural growth driving budburst.
\end{enumerate}

\item Advantages of our approach
\begin{enumerate}
\item In this study we present data comparing phenological cue resposnes for two forest communities from across North America, providing insights acorss a greater geographic scale and diversity of species. 
\item For many of our focal 
\item Our methods differ from previous studies---many studies rely entirely on field chilling---none of our cuttings experience full chilling in the field
\item Our treatments are artificial and do not accurately replicate natural temporal variation in temperature plants experience in the field during winter and spring conditions (Erez1988, Luedeling2009)
\item Limited understanding of dormancy for our focal species---for some spp first time included in phenological experiment
\item bc saw strong chilling response, can assume that we sampled spp while still in endodormancy.
\end{enumerate}
\end{enumerate}
% 



% \item Other species contrast prev work---look at Zohner2016- Alnus incana and Aronia melancarpa---not responsive to photoperiod
% \end{enumerate}
% 
% \item Species diff in relative importance of cue support existence of unique temporal niches across forest communities  (Fig. \ref{supp-fig:cueSp})  
% \begin{enumerate}
% \item Failed for find clear gradients in how cues relate to timing bb
% \item Weak relationship with stronger cue requirements in later bb species
% \item Specific sp example that meet our expectations---e.g. strong photoperiod cues for F.sylvatica like found in other studies
% \item of the lowest quarter species - x were shrubs
% \item May be an oversimplification to groups species cue responses based on coarse categories like functional group
% \end{enumerate}
% 
% \item Differences between the western and eastern populations
% \begin{enumerate}
% \item Across our populations, did find differences between cue responses in western species versus eastern species.
% \item 3 species that occur in both
% \end{enumerate}





% \bibliographystyle{bibliography/bibstyles/amnat.bst}% 
% \bibliography{bibliography/phenoBCBib.bib}


\end{document}