\documentclass{article}

% required 
\usepackage[hyphens]{url} % this wraps my URL versus letting it spill across the page, a bad habit LaTeX has

\usepackage{Sweave}
\usepackage{graphicx}
\usepackage{natbib}
\usepackage{amsmath}
\usepackage{textcomp}%amoung other things, it allows degrees C to be added
\usepackage{float}
\usepackage[utf8]{inputenc} % allow funny letters in citaions 
\usepackage[nottoc]{tocbibind} %should add Refences to the table of contents?
\usepackage{amsmath} % making nice equations 
\usepackage{listings} % add in stan code
\usepackage{xcolor}
\usepackage{capt-of}%alows me to set a caption for code in appendix 
\usepackage[export]{adjustbox} % adding a box around a map
\usepackage{lineno}
\linenumbers
% recommended! Uncomment the below line and change the path for your computer!
% \SweaveOpts{prefix.string=/Users/Lizzie/Documents/git/teaching/demoSweave/Fig.s/demoFig, eps=FALSE} 
%put your Fig.s in one place! Also, note that here 'Fig.s' is the folder and 'demoFig' is what each 
% Fig. produced will be titled plus its number or label (e.g., demoFig-nqpbetter.pdf')
% make your captioning look better
\usepackage[small]{caption}

\usepackage{xr-hyper} %refer to Fig.s in another document
\usepackage{hyperref}

\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{0pt}
\setlength{\belowcaptionskip}{10pt}

% optional: muck with spacing
\topmargin -1.5cm        
\oddsidemargin 0.5cm   
\evensidemargin 0.5cm  % same as oddsidemargin but for left-hand pages
\textwidth 15.59cm
\textheight 21.94cm 
% \renewcommand{\baselinestretch}{1.5} % 1.5 lines between lines
\parindent 0pt		  % sets leading space for paragraphs
% optional: cute, fancy headers
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead[LO]{Draft summer 2023}
\fancyhead[RO]{Temporal Ecology Lab}
% more optionals! %

\graphicspath{ {./figures/} }% tell latex where to find photos 
\externaldocument[supp-]{phenoNAmPhylo_SM}
\begin{document}
\renewcommand{\bibname}{References}%names reference list 

\SweaveOpts{concordance=TRUE} % For RStudio hiccups


\title{Evolutionary history---more than phenological cues---explain temporal assembly of woody plant communities}
\date{\today}
\author{Deirdre Loughnan$^1$ and E M Wolkovich$^1$}
\maketitle 

$^1$ Department of Forest and Conservation, Faculty of Forestry, University of British Columbia, 2424 Main Mall
Vancouver, BC, Canada, V6T 1Z4. \\

Corresponding Author: Deirdre Loughnan, deirdre.loughnan@ubc.ca \\


<<label=runcode1,  echo=FALSE>>=

source("..//rcode/phenologyMsValues.R")
@

\section*{Discussion}

%EMWNov6: Looks like you just started writing! So I will do what I can on comments while looking at an outline PDF without a rnw that matches it ... for the below: good content here, but watch out for passive voice and flow. It's okay for this opening part to be a paragraph or two. 
In our study of woody plant budburst phenology across North America, we found the assembly of species' temporal niche to be partly explained by environmental cues, with little variation explained by different populations. Species within each of our two communities varied considerably in the timing of their budburst and in their responses to environmental cues. While species phenology is largely shaped by temperature and light cues, we found evidence of strong phylogenetic structuring to species budburst phenology as well.\\

\subsection*{Temporal assembly across North America} 

While our western and eastern forest communities differ in both their species composition and local environments, under a controlled environment, budburst phenology and cue responses only differed slightly across populations. This contrasts our expectation of local habitats selection, as we would expect different selective pressures across populations to lead to differences in cues responses. Overall, the timing of budburst was only slightly earlier in our eastern populations when compared to western populations (Fig \ref{fig:siteCues}). These negligible differences could be due to the difference in the timing of sample collection, with our eastern species being collected later in the season and therefore receiving greater field chilling than species in our western growth chamber study. \\


We also found no latitudinal gradients across populations despite differences in local photoperiods (Fig \ref{fig:siteCues}), contrasting the findings of previous work in which poleward populations experienced later budburst (Lieth1974, Zettlemoyer2021). %EMWNov6: can you add a sentence guessing at why you saw differences? I don't know the other studies, but usually I can think of methodological differences (sampling later when chilling might matter already, or using observational data where teasing out photoperiod is harder ... 
The lack of population-level trends in budburst suggests the drivers that determine the timing of budburst are not shaped by current geography, at least at our continental scale. \\ %emwOct31 -- somewhere may want to mention high interannual variation in climate may explain this (combined with selection to match it for early season), see Alina's ms

\subsection*{Community composition and interspecific variation in phenology}

\item Species varied considerably in the responses to our three environmental cues. %EMWNov6: Make this a discussion topic sentence by saying what this means, not just the results .. maybe: Species varied considerably in the responses to our three environmental cues, which translates into large potential differences in budburst timing within each community we sampled. 
The timing of budburst differed by species, with timing from early to late budbursting species spanning a similar period as observed in natural communities (Maycock1961). This suggests our experiment captured a realistic breadth in phenology within temperate forest communities. In general, all of our focal species showed some degree of a response to each of the environmental cues, with responses that were consistent with previous studies. Of our three cues, chilling had the strongest effect, while photoperiod had the weakest. But collectively, we found complex interactions between cues that are advantageous under warming climates \citep{Heide1993,Caffarra2011,Flynn2018}. %EMWNov6:  you probably need to unpack this a little with an example or such: if species responded only to ... 
While species differed in their cue responses, we did not find the clear, generalizable trends we expected across species with similar growth strategies.  \\ %EMWNov6: good transition
% awkward phrasing---needs work

%EMWNov6: nice opening
Despite shrub and tree species differ greatly in their physiology, filling different ecological niche space, we found little variation in their cue responses on a whole. Most of our tree species budburst later than the shrubs species, an order which is in line with previous work (Panchen2014, Yu2015). But, in contrast to our expectations, we found about a quarter of tree species also budburst early, with timing more similar to that of shrub species. Similarly, we found a third of our shrubs species to budburst at similar times as the majority of our tree species. This deviation from our expectations for how shrub and tree species partition their budburst timing suggesting there is more nuance to these patterns than previously found. %By studying such a large assemblage of species, were are able to detect these overarching trends across groups of species.
%Sun2006---found trees and shrubs to leaf out together
As trees species advance phenologically---which is predicted to result in earlier canopy closure and reduced light availability (Donnelly2019)---shrub speceis that are less responsive to changing conditions will experience reduced fitness. But our finding suggests many shrub species have similar cue responses and are likely to also advance with warming. These species have the potential to maintain their relative temporal niche space within a community and mitigate potential effects on community composition and dynamics.\\
%\item Provides novel insights into how species in the understory and canopy layer may respond differently to changes in temperature cues.

%EMWNov6:  'selecting for' likely the wrong thing below ... I suggest avoid talking about selection so much unless you have evidence for it or need it specifically, here you could talk about phenology as part of a suite of traits that operate together -- that's really all I think you mean, as you don't know so much about selection. 
The number of shrub and tree species exhibiting later than expected budburst phenologies indicates that the cues we think are important for budburst may also be selecting for other functional traits. 
we lack a sufficient understanding of the Below, I think selection works as you explain it more.
Selection for earlier budburst may correlate with traits related to light capturing and photosynthesis in understory by shrub species or nutrient uptake in trees species associated with early successional stages or disturbance regimes. Species that differ in their temporal niche will experience different fitness outcomes as determined by their overall suite of traits. But currently we lack a sufficient understanding of the mechanisms that underlie these trait relationships. By incorporating phenology into a broader trait framework we can gain greater insights into the considerable phenotypic variation observed within species functional groups. \\ %EMWNov6: maybe print out and edit by pen for wordiness, such as: we lack a sufficient understanding of the 

\subsection*{Community assembly in responses to cues versus evolutionary history}

%EMWNov6: I would have one paragraph focused on these three organizing levels, then try to explain what your results mean for each in turn ... population, then species, then community (rank order? Has that been discussed yet?), then tweak your last sentence to be something like: But we cannot simply focus ideas of community assembly on species cues, as species phenotypes ...  Or, you could do just population and species here, then keep your phylo paragraphs, then end on a paragraph that takes the cues + phylo and discusses community. 
With continued warming, accurate forecasting of the timing of spring growth will depend on our understanding of cue responses at the population, species and community levels. Within a community, species varied in their timing of budburst by several weeks, but the similarity across populations suggests strong niche conservatism within species with little change in response to local habitats. %emwOct31 -- when you write this up, may want to define niche conservatism the first time you use it (and then always use that definition). I also might avoid stabilizing selection here unless you're sure ... this actually might be a good place to discuss the inter-annual variation driving one set of cues that work across inter-annual and thus potentially large spatial scales 
This lack of population-level differences may be driven by high interannual variability in climate, as it would be advantagious for species to respond to one set of cues that selects for the optimal timing of budburst across years and at large spatial scales. While the effects of population-level variation on cue responses appears be negligible, individual species within community assemblages do differ in their responses to cue (Fig 5). Species' budburst responses were dependent on the magnitude of cues experienced. 
%EMWNov6: I don't get the leap about warming -- is that because forcing and chilling cues are biggest? You need to explain a little fore the reader and I think you have two paragraphs here.... 
As such, populations that are warming at a faster rate will exhibit the greatest budburst advances and changes in species burburst order (Fig 5 \& S4), thereby altering community dynamics and species interactions. But we can not simply focus on current cue responses, as species' current phenotypes are the result of multiple interacting and complex environmental cues that have shaped species over evolutionary time scales (Ackerly2009).\\ %emwOct25 -- good, be sure to contrast somewhere timescales: we see effects of 'deep' time that matter to really short-term predictions (CC forecasting) %DLOct26 --- see below Line 152
\end{enumerate}

% \item In accounting for the effects of species' phylogeny, we found a high level of phylogenetic relatedness among clades of species in the timing of budburst. %emwOct25 -- this is a results sentence ... can you make it more of a Discussion sentence. What does this result mean to readers?
The high degree of phylogenetic relatedness among species suggests that species with shared ancestry, and presumably more similar phenotypes and growth strategies, exhibit similar timing in budburst. A high proportion of variation in budburst was explained by species' level effects, with the differing cues of different species explaining about two-thirds of variation in budburst (Fig \ref{fig:cueGrad}). While we include the three cues mostly commonly attributed to species spring phenology, this finding suggests our model of what drives spring phenology is incomplete.  %emwOct31 -- I wouldn't say 'only' unless you explain why you mean 'only' (i.e., this suggests our model of what drives spring phenology is incomplete... then, you get to phylogeny)
% \item Our study applied extreme differences in cues to test for responses---useful for longer-term predictions/parameterizing process based models---but variation due to phylogenetic structure likely underestimated  %emwOct31 -- why do you think its underestimated? Maybe cut this -- you have a lot now and good stuff. 
%EMWNov6: below sentence needs some work and likely a couple sentences. I would build on the previous sentence about our model of phenology -- we think of phenology as a highly plastic trait and expect differences in cues across years and geography to drive variation in budburst timing, but we're missing something ... and our results suggest evolutionary history is part of that missing story
We were surprised to find that evolutionary history had a large effect on budburst phenology, given that phenology is thought of as a highly plastic trait and expect local conditions to drive variation in the type and magnitude of cue responses. But our findings indicate there are other unidentified latent traits---such as additional physiological traits---that contribute to the phylogenetic structuring, and ultimately temporal niche, of temperate forest communities. By not accounting for the additional cues or traits driving spring phenology, we have a limited ability to predict how communities will respond to continued changes in climate.\\ %emwOct31 -- phylogeny and latent traits would work here (move up some of the item below)

%EMWNov6: you have a lot of species' species and specie's -- I would just use species throughout!
The evolutionary history and ancestral phenotype of a species has the potential to effect their ability to adapt to future climates. Specie's traits are shaped over 'deep' timescales, with the potential for this previous evolution to influencing species' responses to recent climate change today. There is the potential for the previous evolution of a specie's traits shaped over 'deep' timescales to influencing species' responses to recent climate change today. This could limit species from adaptating to new environmental conditions, if they are physiologically constrained by their ancestral phenotype. %emwOct31 -- if they're not optimum today, we never should assume they were in the past ... 
Such phylogenetic constraints could skew species assemblages, favouring species with traits and cue requirements adapted for warmer climates. Species with low chilling and photoperiod requirements would be better able to track and benefit from future climate conditions. But the phylogenetic trends we observed could also indicate our focal speices have had limited evolutionary time to adapt. Some temperate species, like \emph{Nyssa} and \emph{Fagus}, have had a shorter geologic time in which to adapt to their local temperatures, especially in populations at northern range limits such as the ones we sampled.\\
% \item Identifying how and to what extent latent traits contribute to the phylogenetic structuring of temperate forest communities = unknown, but important if we are to predict how communities will respond to continued changes in climate. %emwOct31 -- I would discuss this in the context mentioned above and cut here 


\subsection*{Predicting budburst phenology under future climates} 
Our results provide new insights into the key factors and ecological processes that are critical to forecasting future phenoloiges under climate change. We found strong evidence that changes in budburst cues will produce consistent trends across populations. This allows us to forecast across populations for which we have limited local phenological data but similar species assemblages. The high phylogenetic structure in budburst timing also allows us to use our existing knowledge of species' phenological cue responses to forecasts trends in phylogenetically related species. But we must also be cautious in our assumptions and the inferences we can make. %emwOct31 -- but carefully, see refs in the ospree phylo ms on the dangers of imputation %EMWNov6: this last sentence is pretty vague and general, see Nacho's phylo ms for a better approach, you could probably suggest some specific clades within your study that you might be okay forecasting to and give them as examples
We did not find strong general trends at coarser taxonomic groups, with unexpected trends in species budburst across shrubs and trees, suggesting there are still selective pressures shaping spring phenology we have yet to understand. \\
% \item While our approach address many of the challenges to predicting species responses to further climate change---complexity of regional and increasingly variable seasonality
% \item And yet, our findings highlight our limited understanding of the factors underlying phenological variation within forest communities and groups of species.


%What are the next steps based on what we learned? 
%EMWNov6:  good stuff but needs some work, and sounds a but repetitive currently. 
Our ability to predict changes in spring phenology and mitigate the cascading effects on forest communities is increasingly urgent in light of anthropogenic climate change. To meet this challenge requires community wide approaches such as ours, which is one of the first to include these three types of drivers at a large geographic scale and across forest communities. This appraoch is critical as it provides a greater diversity of species responses and insights into how communities as a whole will respond. To forecast future changes, we need to identify the key underlying ancestral traits that link species' evolutionary histories and are driving the high spp variability observed within temperate forest communities.\\

\end{document}