\documentclass{article}

% required 
\usepackage[hyphens]{url} % this wraps my URL versus letting it spill across the page, a bad habit LaTeX has

\usepackage{Sweave}
\usepackage{graphicx}
\usepackage{natbib}
\usepackage{amsmath}
\usepackage{textcomp}%amoung other things, it allows degrees C to be added
\usepackage{float}
\usepackage[utf8]{inputenc} % allow funny letters in citaions 
\usepackage[nottoc]{tocbibind} %should add Refences to the table of contents?
\usepackage{amsmath} % making nice equations 
\usepackage{listings} % add in stan code
\usepackage{xcolor}
\usepackage{capt-of}%alows me to set a caption for code in appendix 
\usepackage[export]{adjustbox} % adding a box around a map
\usepackage{lineno}
\linenumbers
% recommended! Uncomment the below line and change the path for your computer!
% \SweaveOpts{prefix.string=/Users/Lizzie/Documents/git/teaching/demoSweave/Fig.s/demoFig, eps=FALSE} 
%put your Fig.s in one place! Also, note that here 'Fig.s' is the folder and 'demoFig' is what each 
% Fig. produced will be titled plus its number or label (e.g., demoFig-nqpbetter.pdf')
% make your captioning look better
\usepackage{caption}
\usepackage{subcaption}
 \captionsetup[subfigure]{labelformat=simple, position=top, labelfont=bf,textfont=normalfont,singlelinecheck=off,justification=raggedright, font = normal}
 
\usepackage{xr-hyper} %refer to Fig.s in another document
\usepackage{hyperref}
\externaldocument{phenoNAmPhylo} 

\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{0pt}
\setlength{\belowcaptionskip}{10pt}

% optional: muck with spacing
\topmargin -1.5cm        
\oddsidemargin 0.5cm   
\evensidemargin 0.5cm  % same as oddsidemargin but for left-hand pages
\textwidth 15.59cm
\textheight 21.94cm 
% \renewcommand{\baselinestretch}{1.5} % 1.5 lines between lines
\parindent 0pt		  % sets leading space for paragraphs
% optional: cute, fancy headers
% \usepackage{fancyhdr}
% \pagestyle{fancy}
% \fancyhead[LO]{Draft early 2022}
% \fancyhead[RO]{Temporal Ecology Lab}
% more optionals! %

\graphicspath{ {../figures/} }% tell latex where to find photos 
\begin{document}



\SweaveOpts{concordance=TRUE} % For RStudio hiccups


\title{Supplementary Material: Current environments and evolutionary history shape forest temporal assembly}
\date{\today}
\author{Deirdre Loughnan$^1$ and E M Wolkovich$^1$}
\maketitle 

\renewcommand{\thetable}{S\arabic{table}}
\renewcommand{\thefigure}{S\arabic{figure}}
\renewcommand{\labelitemi}{$-$}

\begin{table}[ht]
\centering
\caption{Approximate chill units from our two western sites, E.C. Manning Park and Smithers B.C., Canada, and our two eastern sites, Harvard Forest, USA and St. Hippolyte, Canada. Weather data was obtained from the Hope Slide weather station for our E.C. Manning Park estimates and the Smithers airport weather station for our Smithers communities. For our eastern communities, weather data was obtained from weather stations at Harvard Forest and in St. Hippolyte.} 
\label{tabChill}
\begin{tabular}{llrrr}
  \hline
Population & Chilling treatment & Chill hours & Utah model & Chill portions \\ 
  \hline
Harvard forest & Field chilling & 892 & 814.50 & 56.62 \\ 
  Harvard forest & Field chilling + 30 d at 4$^\circ$C & 2140 & 2062.50 & 94.06 \\ 
  St. Hippoltye & Field chilling & 682 & 599.50 & 44.63 \\ 
  St. Hippoltye & Field chilling + 30 d at 4$^\circ$C & 1930 & 1847.50 & 82.06 \\ 
  Smithers & Field chilling + 30 d at 4$^\circ$C & 1317 & 1368.00 & 54.95 \\ 
  Smithers & Field chilling + 70 d at 4$^\circ$C & 1965 & 2016.00 & 74.67 \\ 
  Manning Park & Field chilling + 30 d at 4$^\circ$C & 1213 & 1377.00 & 55.09 \\ 
  Manning Park & Field chilling + 70 d at 4$^\circ$C & 1861 & 2025.00 & 75.33 \\ 
  \end{tabular}
\end{table}


% <<label= tabChill, echo=FALSE , results=tex>>=
% 
% # Chill units from our two western sites, E.C. Manning Park and Smithers B.C., and our two eastern sites, Harvard Forest (HF) USA and St. Hippolyte(SH) Canada.
% 
% require(xtable)
% #library(tidyr)
% chill <- read.csv("..//output/chillUnits.csv")
% chill$Chilling.treatment<- gsub("degree ","$\\circ$", chill$Chilling.treatment)
% names(chill) <- c("Population","Chilling treatment","Chill hours","Utah model","Chill portions")
% 
% # chillunit <- xtable(chill, caption = "Chill units from our two western sites, E.C. Manning Park (MP) and Smithers B.C.(SM) Canada, and our two eastern sites, Harvard Forest (HF) USA and St. Hippolyte(SH) Canada.", label = "tableChill")
% print(xtable(chill, caption = "Approximate chill units from our two western sites, E.C. Manning Park and Smithers B.C., Canada, and our two eastern sites, Harvard Forest, USA and St. Hippolyte, Canada. Weather data was obtained from the Hope Slide weather station for our E.C. Manning Park estimates and the Smithers airport weather station for our Smithers communities. For our eastern communities, weather data was obtained from weather stations at Harvard Forest and in St. Hippolyte", label = "tabChill"),include.rownames= F, caption.placement="top", hline.after=c(-1,0))
% @

\begin{figure}[ht]
\centering
\begin{subfigure}{0.28\textwidth}
\centering
\hfill
\caption{Forcing}
\vspace{-0.5\baselineskip}
\label{Forcing}
    \includegraphics[scale = 0.75]{..//..//pheno_bc/figures/intrxnPlots8Chill3LataCrop.pdf}%,
\end{subfigure}
\begin{subfigure}{0.28\textwidth}
\centering
\hfill
\caption{Chilling}
\vspace{-0.5\baselineskip}
\label{Chilling}
    \includegraphics[scale = 1]{..//..//pheno_bc/figures/intrxnPlots8Chill3LatbCrop.pdf}%,
\end{subfigure}
\begin{subfigure}{0.38\textwidth}
\centering
\hfill
\caption{Photoperiod}
\vspace{-0.5\baselineskip}
\label{Photoperiod}
    \includegraphics[scale = 1.5]{..//..//pheno_bc/figures/intrxnPlots8Chill3Latc.pdf}%,
\end{subfigure}
     \caption{Estimated day of budburst in response to \textbf{a,} forcing across populations under low chilling and short photoperiods, \textbf{b,} chilling across populations under low forcing and short photoperiods, and \textbf{c,}  across photoperiods under low forcing and chilling for species sampled from our four populations. The thin error bars represent the 90\% uncertainty interval, while the thicker error bars represent the 50\% uncertainty interval, and symbols the mean.} 
    \label{fig:intrxn3}
\end{figure}
\newpage

\begin{figure}[h!]
    \centering
     \includegraphics[width=\textwidth]{..//..//pheno_bc/figures/cueST28Chill.pdf}
    \caption[Comparison of cues by functional groups]{Comparisons of posterior distributions for cues estimates between shrub and tree species. Black circles represent the median cues, while the thinner black line the 90\% quantile interval. The coloured distribution is the posterior density of cues responses for all species within a given architectural type. The y-axis spans the entire range of the data.}
    \label{fig:cueST}
    \end{figure}
    
\begin{figure}[ht]
\centering
\begin{subfigure}{0.28\textwidth}
\centering
\hfill
\caption{}
\vspace{-1.8\baselineskip}
\label{}
    \includegraphics[width=1.8in]{..//..//pheno_bc/figures/rankstiBBTransecta.pdf}%,
\end{subfigure}
\begin{subfigure}{0.28\textwidth}
\centering
\hfill
\caption{}
\vspace{-1.8\baselineskip}
\label{}
    \includegraphics[width=1.8in]{..//..//pheno_bc/figures/rankstiBBTransectb.pdf}%,
\end{subfigure}
\begin{subfigure}{0.28\textwidth}
\centering
\hfill
\caption{}
\vspace{-1.8\baselineskip}
\label{}
    \includegraphics[width=1.8in]{..//..//pheno_bc/figures/rankstiBBTransectc.pdf}%,
\end{subfigure}
\begin{subfigure}{0.28\textwidth}
\centering
\hfill
\caption{}
\vspace{-1.8\baselineskip}
\label{}
    \includegraphics[width=1.8in]{..//..//pheno_bc/figures/rankstiBBTransectd.pdf}%,
\end{subfigure}
\begin{subfigure}{0.28\textwidth}
\centering
\hfill
\caption{}
\vspace{-1.8\baselineskip}
\label{}
    \includegraphics[width=1.8in]{..//..//pheno_bc/figures/rankstiBBTransecte.pdf}%,
\end{subfigure}
\begin{subfigure}{0.28\textwidth}
\centering
\hfill
\caption{}
\vspace{-1.8\baselineskip}
\label{}
    \includegraphics[width=1.8in]{..//..//pheno_bc/figures/rankstiBBTransectf.pdf}%,
\end{subfigure}
     \caption[Species ranked by estimated budburst dates]{Estimated changes in species ranked budburst order, \textbf{a} \& \textbf{d} compared between species level effects (species intercept) and under high cues, species level effects and under low cues, \textbf{b} \& \textbf{e}, and ranked order under low and high cues, \textbf{c} \& \textbf{f}, for our eastern species in red (\textbf{a-c}) and western species in blue (\textbf{d-f}). For the three species that occur in both transect, shown in yellow, \emph{Alnus incana} exhibited the greatest rank change with a difference of three, while \emph{Betula papyrifera} had a rank difference of two and \emph{Populus tremuloides} a rank difference of one.}
    \label{fig:rank}
\end{figure}

\begin{figure}[!ht]
    \centering
     \includegraphics[width=\textwidth]{..//..//pheno_bc/figures/changes_pheno_4sites8Chill.pdf}
    \caption[Estimated response in budburst to varying cues]{Estimated mean responses in budburst date of first bud to varying forcing, chilling, and photoperiod cues for 47 deciduous woody species across North America. Points represent mean posterior estimates, while bars depict the 90\% uncertainty interval. Negative responses represent advances in budburst, while positive values represent delaying effects. }
    \label{fig:muplot}
\end{figure}

\begin{figure}[h!]
    \centering
     \includegraphics[width=\textwidth]{..//..//pheno_bc/figures/phyloIntColor.pdf}
     \caption[Phylogeny of woody plant species]{Species differences were accounted for by including phylogenetic effects on the species intercept in a model estimating days to budburst after the start of forcing treatments. We pruned to our species subset an existing phylogeny for flowering plants developed by Smith and Brown (2018).} %emwOct25 -- add units to intercept (days) on figure.
    \label{fig:phylo}
\end{figure}


\begin{table}[ht]
\centering
\caption{Mean budburst dates across all treatments from raw data for 47 species at our two western sites, E.C. Manning Park and Smithers B.C., Canada, and our two eastern sites, Harvard Forest, USA and St. Hippolyte, Canada.} 
\label{tabPhenoSp}
\begin{tabular}{lrrrr}
  \hline
Species & Harvard Forest & St. Hippoltye & Manning Park & Smithers \\ 
  \hline
\emph{Acer glabrum} &  &  & 36 & 39 \\ 
  \emph{Acer pensylvanicum} & 16 & 18 &  &  \\ 
  \emph{Acer rubrum} & 22 & 25 &  &  \\ 
  \emph{Acer saccharum} & 45 & 36 &  &  \\ 
  \emph{Alnus incana} &  &  & 28 & 30 \\ 
  \emph{Alnus incana} & 33 & 25 &  &  \\ 
  \emph{Alnus viridis} &  &  & 44 & 43 \\ 
  \emph{Amelanchier alnifolia} &  &  & 19 & 18 \\ 
  \emph{Aronia melanocarpa} & 14 &  &  &  \\ 
  \emph{Betula alleghaniensis} & 20 & 21 &  &  \\ 
  \emph{Betula lenta} & 30 &  &  &  \\ 
  \emph{Betula papyrifera} &  &  &  & 31 \\ 
  \emph{Betula papyrifera} & 17 & 18 &  &  \\ 
  \emph{Corylus cornuta} & 25 & 19 &  &  \\ 
  \emph{Cornus stolonifera} &  &  & 15 & 17 \\ 
  \emph{Fagus grandifolia} & 42 & 43 &  &  \\ 
  \emph{Fraxinus nigra} & 38 & 38 &  &  \\ 
  \emph{Hamamelis virginiana} & 44 &  &  &  \\ 
  \emph{Ilex mucronata} & 16 & 15 &  &  \\ 
  \emph{Kalmia angustifolia} & 30 & 32 &  &  \\ 
  \emph{Lonicera canadensis} & 17 & 16 &  &  \\ 
  \emph{Lonicera involucrata} &  &  & 22 & 20 \\ 
  \emph{Lyonia ligustrina} & 31 &  &  &  \\ 
  \emph{Menziesia ferruginea} &  &  & 43 & 46 \\ 
  \emph{Nyssa sylvatica} & 32 &  &  &  \\ 
  \emph{Populus balsamifera} &  &  & 30 & 31 \\ 
  \emph{Populus grandidentata} & 33 & 31 &  &  \\ 
  \emph{Populus tremuloides} &  &  & 46 & 35 \\ 
  \emph{Prunus pensylvanica} & 18 & 16 &  &  \\ 
  \emph{Quercus alba} & 45 &  &  &  \\ 
  \emph{Quercus rubra} & 36 & 34 &  &  \\ 
  \emph{Quercus velutina} & 52 &  &  &  \\ 
  \emph{Rhamnus frangula} & 32 &  &  &  \\ 
  \emph{Rhododendron albiflorum} &  &  & 19 &  \\ 
  \emph{Rhododendron prinophyllum} & 29 &  &  &  \\ 
  \emph{Ribes lacustre} &  &  & 29 & 23 \\ 
  \emph{Rubus parviflorus} &  &  & 28 & 30 \\ 
  \emph{Sambucus racemosa} &  &  & 33 &  \\ 
  \emph{Shepherdia canadensis} &  &  & 25 & 24 \\ 
  \emph{Sorbus scopulina} &  &  & 21 & 19 \\ 
  \emph{Spiraea alba} & 18 & 20 &  &  \\ 
  \emph{Spiraea betulifolia} &  &  & 24 & 18 \\ 
  \emph{Spiraea pyramidata} &  &  & 26 & 22 \\ 
  \emph{Symphoricarpos albus} &  &  & 27 & 32 \\ 
  \emph{Vaccinium membranaceum} &  &  & 22 & 23 \\ 
  \emph{Vaccinium myrtilloides} & 13 & 17 &  &  \\ 
  \emph{Viburnum cassinoides} & 15 & 18 &  &  \\ 
  \emph{Viburnum edule} &  &  & 19 & 8 \\ 
  \emph{Viburnum lantanoides} & 31 & 28 &  &  \\ 
  \end{tabular}
\end{table}

% %emwOct25 -- italicize spp names
% <<label= meanBBTab, echo=FALSE , results=tex>>=
% # Mean bb dates across all treatments from raw data for 47 species at our two western sites, E.C. Manning Park and Smithers B.C., and our two eastern sites, Harvard Forest (HF) USA and St. Hippolyte(SH) Canada.
% 
% require(xtable)
% #library(tidyr)
% require(reshape2)
% require(stringr)
% require(plyr)
% 
% dl <- read.csv("..//input/dl_allbb_mini.csv")
% 
% temp <- str_split_fixed(dl$trt, "_", 3)
% dl$chill<- temp[,1]
% dl$photo <- temp[,2]
% dl$force <- temp[,3]
% 
% dl.chill <- read.csv("..//input/chilling_values_Hope_Smithers.csv")
% 
% dl.wchill <- merge(dl, dl.chill, by = c("population","chill"))
% dl.wchill$lab3 <- dl.wchill$lab2
% dl.wchill$lab2 <- paste(dl.wchill$species, dl.wchill$population, dl.wchill$rep, sep = "_")
% dl.wchill$transect <- "west"
% 
% df <- read.csv("..//input/df_dxb_prepped_data.csv")
% df.chill <- read.csv("..//input/chilling_values_eastern.csv")
% df.wchill <- merge(df, df.chill, by =c("population","chill"))
% df.wchill <- df.wchill[, c("population", "chill","force","photo","lab2", "bb","species", "treatment","Chill_portions","Utah_Model")]
% df.wchill$transect <- "east"
% 
% # # mergeing the my data with DF
%  pheno <- rbind.fill(dl.wchill, df.wchill)
% 
% meanBB <- aggregate(pheno["bb"], pheno[c("population", "species")], FUN = mean, na.rm  =T)
% meanBB$bb <- round(meanBB$bb, 0)
% 
% meanBBPop <- dcast(meanBB, species ~ population, value.var = "bb")
% meanBBPop$species <- tolower(meanBBPop$species)
% 
% spInfo <- read.csv("..//input/species_list.csv")
% spInfo$species.name <- gsub("_"," ", spInfo$species.name)
% spInfo$species.name <- paste("\\emph{", spInfo$species.name, "}", sep = "")
% mdlTab <- merge(meanBBPop, spInfo, by = "species")
% mdlTab <- mdlTab[, c("species.name","HF","SH","mp","sm")]
% 
% colnames(mdlTab) <- c("Species" , "Harvard Forest", "St. Hippoltye","Manning Park", "Smithers")
% 
% meanBBTab <- xtable(mdlTab, caption="Mean budburst dates across all treatments from raw data for 47 species at our two western sites, E.C. Manning Park (MP) and Smithers B.C.(SM) Canada, and our two eastern sites, Harvard Forest (HF) USA and St. Hippolyte (SH) Canada.")
% print(meanBBTab,include.rownames=F, caption.placement="top", hline.after=c(-1,0), sanitize.text.function = identity,digits=c(0,0,0,0,0))
% 
% @
% 


<<label=bbSuccess, echo=FALSE, results=tex >>=
spwithbb <- read.csv("..//output/bb.success.ax.trt.csv", head = TRUE)
library(xtable)

spInfo <- read.csv("..//input/species_list.csv")
spInfo$species.name <- gsub("_"," ", spInfo$species.name)
spInfo$species.name <- paste("\\emph{", spInfo$species.name, "}", sep = "")
colnames(spInfo) <- c("Species name", "Species","Plant type", "transect")
bb_suc <- merge(spwithbb, spInfo, by = "Species")

bb_suc <- bb_suc[, c("Species name", "Proportion.Budburst","Plant type")]
names(bb_suc) <- c("Species name", "Proportion budburst","Plant type")

make.bb_suc <- xtable(bb_suc,caption="Proportion of surviving samples per species for which budburst was observed in our western controlled enviornment study. See Flynn and Wolkovich (2018) for survival in our eastern study.",label = "tabSurv")
print(make.bb_suc,include.rownames=F, caption.placement="top", hline.after=c(-1,0), sanitize.text.function = identity)

@

\end{document}