\documentclass{article}

% required 
\usepackage[hyphens]{url} % this wraps my URL versus letting it spill across the page, a bad habit LaTeX has

\usepackage{Sweave}
\usepackage{graphicx}
\usepackage{natbib}
\usepackage{amsmath}
\usepackage{textcomp}%amoung other things, it allows degrees C to be added
\usepackage{float}
\usepackage[utf8]{inputenc} % allow funny letters in citaions 
\usepackage[nottoc]{tocbibind} %should add Refences to the table of contents?
\usepackage{amsmath} % making nice equations 
\usepackage{listings} % add in stan code
\usepackage{xcolor}
\usepackage{capt-of}%alows me to set a caption for code in appendix 
\usepackage[export]{adjustbox} % adding a box around a map
\usepackage{lineno}
\linenumbers
% recommended! Uncomment the below line and change the path for your computer!
% \SweaveOpts{prefix.string=/Users/Lizzie/Documents/git/teaching/demoSweave/Fig.s/demoFig, eps=FALSE} 
%put your Fig.s in one place! Also, note that here 'Fig.s' is the folder and 'demoFig' is what each 
% Fig. produced will be titled plus its number or label (e.g., demoFig-nqpbetter.pdf')
% make your captioning look better
\usepackage{caption}
\usepackage{subcaption}
 \captionsetup[subfigure]{labelformat=simple, position=top, labelfont=bf,textfont=normalfont,singlelinecheck=off,justification=raggedright, font = normal}
 
\usepackage{xr-hyper} %refer to Fig.s in another document

\externaldocument[main-]{phenoNAmPhylo} 

\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{0pt}
\setlength{\belowcaptionskip}{10pt}

% optional: muck with spacing
\topmargin -1.5cm        
\oddsidemargin 0.5cm   
\evensidemargin 0.5cm  % same as oddside margin but for left-hand pages
\textwidth 15.59cm
\textheight 21.94cm 
% \renewcommand{\baselinestretch}{1.5} % 1.5 lines between lines
\parindent 0pt		  % sets leading space for paragraphs
% optional: cute, fancy headers
% \usepackage{fancyhdr}
% \pagestyle{fancy}
% \fancyhead[LO]{Draft early 2022}
% \fancyhead[RO]{Temporal Ecology Lab}
% more optionals! %

\graphicspath{ {../figures/} }% tell latex where to find photos 
\begin{document}

\SweaveOpts{concordance=TRUE} % For RStudio hiccups


\title{Supplementary Material: Current environments and evolutionary history shape forest temporal assembly}
\date{\today}
\author{Deirdre Loughnan$^1$ and E M Wolkovich$^1$}
\maketitle 

\renewcommand{\thetable}{S\arabic{table}}
\renewcommand{\thefigure}{S\arabic{figure}}
\renewcommand{\labelitemi}{$-$}

\begin{figure}[ht]
\centering
    \includegraphics[scale = 0.75]{..//..//pheno_bc/figures/panelFig/intrxnPlots8Chill3Lat_Oct17.pdf}%,
     \caption{Estimated day of budburst in response to \textbf{a,} forcing across sites under low chilling and short photoperiods, \textbf{b,} chilling across sites under low forcing and short photoperiods, and \textbf{c,}  across photoperiods under low forcing and chilling for species sampled from our four sites. The thin error bars represent the 90\% uncertainty interval, while the thicker error bars represent the 50\% uncertainty interval, and symbols the mean.} 
    \label{fig:intrxn3}
\end{figure}
\newpage

\begin{figure}[h!]
    \centering
     \includegraphics[width=\textwidth]{..//..//pheno_bc/figures/panelFig/cueST28Chill_90_Oct17.pdf}
    \caption{Comparisons of posterior distributions for cue estimates between shrub and tree species. Circles represent the mean, while the thicker error bars represent the 50\% uncertainty interval, and thinner line the 90\% quantile interval.}
    \label{fig:cueST}
    \end{figure}
    
\begin{figure}[ht]
\centering
  \includegraphics[width= \textwidth]{..//..//pheno_bc/figures/panelFig/rankstiBBTransect_Oct17.pdf}%,
     \caption{Comparisons of the estimated changes in species ranked budburst order, \textbf{a} \& \textbf{d} between species-level effects (species intercept) and under high cues, species-level effects and under low cues, \textbf{b} \& \textbf{e}, and under low versus high cues, \textbf{c} \& \textbf{f}, for our eastern species (in red, \textbf{a-c}) and western species (in blue, \textbf{d-f}). For the three species that occur in both transect (shown in yellow), \emph{Alnus incana} exhibited the greatest rank change with a difference of three, while \emph{Betula papyrifera} had a rank difference of two and \emph{Populus tremuloides} a rank difference of one.}
    \label{fig:rank}
\end{figure}

% \begin{figure}[!ht]
%     \centering
%      \includegraphics[width=\textwidth]{..//..//pheno_bc/figures/panelFig/changes_pheno_4sites_Oct17.pdf}
%     \caption{Estimated mean responses in budburst timing of the first bud to varying forcing, chilling, and photoperiod cues across 47 deciduous woody species across North America (see Table \ref{tab4Site} for values). Points represent mean posterior estimates, while bars depict the 90\% uncertainty interval. Negative responses represent advances in budburst, while positive values represent delaying effects. }
%     \label{fig:muplot}
% \end{figure}

\begin{figure}[h!]
    \centering
     \includegraphics[width=\textwidth]{..//..//pheno_bc/figures/panelFig/phyloIntColor_Oct17.pdf}
     \caption{Species differences were accounted for by including phylogenetic effects on the species intercept in a model estimating days to budburst after the start of forcing treatments. We pruned to our species subset an existing phylogeny for flowering plants developed by Smith and Brown (2018).} 
    \label{fig:phylo}
\end{figure}

\begin{table}[ht!]
\centering
\caption{Mean budburst dates across all treatments from raw observation data of 47 species at our two western sites, E.C. Manning park and Smithers B.C., Canada, and our two eastern sites, Harvard Forest, USA and St. Hippolyte, Canada.} 
\label{tabPhenoSp}
\begin{tabular}{lrrrr}
  \hline
Species & Harvard forest & St. Hippoltye & Manning park & Smithers \\ 
  \hline
\emph{Acer glabrum} &  &  & 36 & 39 \\ 
  \emph{Acer pensylvanicum} & 16 & 18 &  &  \\ 
  \emph{Acer rubrum} & 22 & 25 &  &  \\ 
  \emph{Acer saccharum} & 45 & 36 &  &  \\ 
  \emph{Alnus incana} &  &  & 28 & 30 \\ 
  \emph{Alnus incana} & 33 & 25 &  &  \\ 
  \emph{Alnus viridis} &  &  & 44 & 43 \\ 
  \emph{Amelanchier alnifolia} &  &  & 19 & 18 \\ 
  \emph{Aronia melanocarpa} & 14 &  &  &  \\ 
  \emph{Betula alleghaniensis} & 20 & 21 &  &  \\ 
  \emph{Betula lenta} & 30 &  &  &  \\ 
  \emph{Betula papyrifera} &  &  &  & 31 \\ 
  \emph{Betula papyrifera} & 17 & 18 &  &  \\ 
  \emph{Corylus cornuta} & 25 & 19 &  &  \\ 
  \emph{Cornus stolonifera} &  &  & 15 & 17 \\ 
  \emph{Fagus grandifolia} & 42 & 43 &  &  \\ 
  \emph{Fraxinus nigra} & 38 & 38 &  &  \\ 
  \emph{Hamamelis virginiana} & 44 &  &  &  \\ 
  \emph{Ilex mucronata} & 16 & 15 &  &  \\ 
  \emph{Kalmia angustifolia} & 30 & 32 &  &  \\ 
  \emph{Lonicera canadensis} & 17 & 16 &  &  \\ 
  \emph{Lonicera involucrata} &  &  & 22 & 20 \\ 
  \emph{Lyonia ligustrina} & 31 &  &  &  \\ 
  \emph{Menziesia ferruginea} &  &  & 43 & 46 \\ 
  \emph{Nyssa sylvatica} & 32 &  &  &  \\ 
  \emph{Populus balsamifera} &  &  & 30 & 31 \\ 
  \emph{Populus grandidentata} & 33 & 31 &  &  \\ 
  \emph{Populus tremuloides} &  &  & 46 & 35 \\ 
  \emph{Prunus pensylvanica} & 18 & 16 &  &  \\ 
  \emph{Quercus alba} & 45 &  &  &  \\ 
  \emph{Quercus rubra} & 36 & 34 &  &  \\ 
  \emph{Quercus velutina} & 52 &  &  &  \\ 
  \emph{Rhamnus frangula} & 32 &  &  &  \\ 
  \emph{Rhododendron albiflorum} &  &  & 19 &  \\ 
  \emph{Rhododendron prinophyllum} & 29 &  &  &  \\ 
  \emph{Ribes lacustre} &  &  & 29 & 23 \\ 
  \emph{Rubus parviflorus} &  &  & 28 & 30 \\ 
  \emph{Sambucus racemosa} &  &  & 33 &  \\ 
  \emph{Shepherdia canadensis} &  &  & 25 & 24 \\ 
  \emph{Sorbus scopulina} &  &  & 21 & 19 \\ 
  \emph{Spiraea alba} & 18 & 20 &  &  \\ 
  \emph{Spiraea betulifolia} &  &  & 24 & 18 \\ 
  \emph{Spiraea pyramidata} &  &  & 26 & 22 \\ 
  \emph{Symphoricarpos albus} &  &  & 27 & 32 \\ 
  \emph{Vaccinium membranaceum} &  &  & 22 & 23 \\ 
  \emph{Vaccinium myrtilloides} & 13 & 17 &  &  \\ 
  \emph{Viburnum cassinoides} & 15 & 18 &  &  \\ 
  \emph{Viburnum edule} &  &  & 19 & 8 \\ 
  \emph{Viburnum lantanoides} & 31 & 28 &  &  \\ 
  \end{tabular}
\end{table}
\newpage

\begin{table}[ht!]
\centering
\caption{Approximate chill units from our two western sites, E.C. Manning park and Smithers B.C., Canada, and our two eastern sites, Harvard Forest, USA and St. Hippolyte, Canada. Weather data for the fall of 2019 and winter 2020 was obtained from the Hope Slide weather station for our E.C. Manning park estimates and the Smithers airport weather station for our Smithers communities. For our eastern communities, weather data for the fall of 2014 and winter 2015 was obtained from weather stations at Harvard Forest and in St. Hippolyte.} 
\label{tabChill}
\begin{tabular}{llrrr}
  \hline
Site & Chilling treatment & Chill hours & Utah model & Chill portions \\ 
  \hline
Harvard forest & Field chilling & 892 & 814.50 & 56.62 \\ 
  Harvard forest & Field chilling + 30 d at 4$^\circ$C & 2140 & 2062.50 & 94.06 \\ 
  St. Hippoltye & Field chilling & 682 & 599.50 & 44.63 \\ 
  St. Hippoltye & Field chilling + 30 d at 4$^\circ$C & 1930 & 1847.50 & 82.06 \\ 
  Smithers & Field chilling + 30 d at 4$^\circ$C & 1317 & 1368.00 & 54.95 \\ 
  Smithers & Field chilling + 70 d at 4$^\circ$C & 1965 & 2016.00 & 74.67 \\ 
  Manning park & Field chilling + 30 d at 4$^\circ$C & 1213 & 1377.00 & 55.09 \\ 
  Manning park & Field chilling + 70 d at 4$^\circ$C & 1861 & 2025.00 & 75.33 \\ 
  \end{tabular}
\end{table}
\newpage

\begin{table}[ht!]
\centering
\caption{Summary output from a phylogenetic Bayesian model in which species are partially pooled and phylogeny is included on the intercept. See the statistical analysis section of the methods for more detail.} 
\label{tab4Site}
\begin{tabular}{rrrrrrr}
  \hline
 & mean & sd & 5\% & 95\% & n\_eff & Rhat \\ 
  \hline
$\alpha_{sp}$ & 30.33 & 2.84 & 25.93 & 35.12 & 2689.65 & 1.00 \\ 
$\lambda$ & 0.41 & 0.20 & 0.07 & 0.74 & 2805.35 & 1.00 \\ 
$\beta_{forcing}$ & -9.55 & 0.74 & -10.70 & -8.30 & 1391.78 & 1.00 \\ 
$\beta_{photoperiod}$ & -3.62 & 0.41 & -4.30 & -3.00 & 3089.29 & 1.00 \\ 
$\beta_{chilling}$ & -15.21 & 1.25 & -17.30 & -13.20 & 2142.42 & 1.00 \\ 
$\beta_{Manning\ park}$ & 2.09 & 0.36 & 1.50 & 2.70 & 4061.13 & 1.00 \\ 
$\beta_{Harvard\ forest}$ & -6.04 & 1.03 & -7.80 & -4.40 & 486.95 & 1.01 \\ 
$\beta_{St.\ Hippolyte}$ & -8.71 & 0.97 & -10.30 & -7.10 & 485.37 & 1.01 \\ 
$\beta_{forcing \times photoperiod}$ & 0.23 & 0.71 & -1.00 & 1.40 & 3698.87 & 1.00 \\ 
$\beta_{forcing \times chilling}$ & 9.06 & 0.90 & 7.60 & 10.50 & 3005.09 & 1.00 \\ 
$\beta_{photoperiod \times chilling}$ & -0.67 & 0.90 & -2.20 & 0.80 & 2690.36 & 1.00 \\ 
$\beta_{forcing \times Manning\ park}$ & -1.76 & 0.77 & -3.00 & -0.50 & 3836.43 & 1.00 \\ 
$\beta_{photoperiod \times Manning\ park}$ & 0.58 & 0.79 & -0.70 & 1.90 & 3375.92 & 1.00 \\ 
$\beta_{chilling \times Manning\ park}$ & -0.36 & 1.60 & -3.00 & 2.20 & 1714.08 & 1.00 \\ 
$\beta_{forcing \times Harvard\ forest}$ & 3.81 & 1.22 & 1.80 & 5.80 & 1752.75 & 1.00 \\ 
$\beta_{photoperiod \times Harvard\ forest}$ & -1.96 & 0.86 & -3.30 & -0.60 & 2877.96 & 1.00 \\ 
$\beta_{chilling \times Harvard\ forest}$ & 9.97 & 2.03 & 6.60 & 13.40 & 911.46 & 1.01 \\ 
$\beta_{forcing \times St.\ Hippolyte}$ & 5.25 & 1.19 & 3.20 & 7.20 & 1659.45 & 1.00 \\ 
$\beta_{photoperiod \times St.\ Hippolyte}$ & -2.13 & 0.84 & -3.50 & -0.70 & 2606.20 & 1.00 \\ 
$\beta_{chilling \times St.\ Hippolyte}$ & 8.65 & 1.70 & 5.90 & 11.50 & 1021.36 & 1.01 \\ 
  \end{tabular}
\end{table}

<<label=bbSuccess, echo=FALSE, results=tex >>=
spwithbb <- read.csv("..//output/bb.success.ax.trt.csv", head = TRUE)
library(xtable)

spInfo <- read.csv("..//input/species_list.csv")
spInfo$species.name <- gsub("_"," ", spInfo$species.name)
spInfo$species.name <- paste("\\emph{", spInfo$species.name, "}", sep = "")
colnames(spInfo) <- c("Species name", "Species","Plant type", "transect")
bb_suc <- merge(spwithbb, spInfo, by = "Species")

bb_suc <- bb_suc[, c("Species name", "Proportion.Budburst","Plant type")]
names(bb_suc) <- c("Species name", "Proportion budburst","Plant type")

make.bb_suc <- xtable(bb_suc,caption="Proportion of surviving samples per species for which budburst was observed in our western controlled enviornment study. See Flynn and Wolkovich (2018) for survival in our eastern study.",label = "tabSurv")
print(make.bb_suc,include.rownames=F, caption.placement="top", hline.after=c(-1,0), sanitize.text.function = identity)

@

\end{document}