\documentclass{article}

% required 
\usepackage[hyphens]{url} % this wraps my URL versus letting it spill across the page, a bad habit LaTeX has

\usepackage{Sweave}
\usepackage{graphicx}
\usepackage{natbib}
\usepackage{amsmath}
\usepackage{textcomp}%among other things, it allows degrees C to be added
\usepackage{float}
\usepackage[utf8]{inputenc} % allow funny letters in citations 
\usepackage[nottoc]{tocbibind} %should add References to the table of contents?
\usepackage{amsmath} % making nice equations 
\usepackage{listings} % add in stan code
\usepackage{xcolor}
\usepackage{capt-of}%allows me to set a caption for code in appendix 
\usepackage[export]{adjustbox} % adding a box around a map
\usepackage{lineno}
\linenumbers
% recommended! Uncomment the below line and change the path for your computer!
% \SweaveOpts{prefix.string=/Users/Lizzie/Documents/git/teaching/demoSweave/Fig.s/demoFig, eps=FALSE} 
%put your Fig.s in one place! Also, note that here 'Fig.s' is the folder and 'demoFig' is what each 
% Fig. produced will be titled plus its number or label (e.g., demoFig-nqpbetter.pdf')
% make your captioning look better
\usepackage[small]{caption}

\usepackage{xr-hyper} %refer to Fig.s in another document
\usepackage{hyperref}

\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{0pt}
\setlength{\belowcaptionskip}{10pt}

% optional: muck with spacing
\topmargin -1.5cm        
\oddsidemargin 0.5cm   
\evensidemargin 0.5cm  % same as oddsidemargin but for left-hand pages
\textwidth 15.59cm
\textheight 21.94cm 
% \renewcommand{\baselinestretch}{1.5} % 1.5 lines between lines
\parindent 0pt		  % sets leading space for paragraphs
% optional: cute, fancy headers
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead[LO]{Draft summer 2023}
\fancyhead[RO]{Temporal Ecology Lab}
% more optionals! %

\graphicspath{ {./figures/} }% tell latex where to find photos 
\externaldocument[supp-]{phenoNAmPhylo_SM}
\begin{document}
\renewcommand{\bibname}{References}%names reference list 

\SweaveOpts{concordance=TRUE} % For RStudio hiccups


\title{Evolutionary history---more than phenological cues---explain temporal assembly of woody plant communities}
\date{\today}
\author{Deirdre Loughnan$^1$ and E M Wolkovich$^1$}
\maketitle 

$^1$ Department of Forest and Conservation, Faculty of Forestry, University of British Columbia, 2424 Main Mall
Vancouver, BC, Canada, V6T 1Z4. \\

Corresponding Author: Deirdre Loughnan, deirdre.loughnan@ubc.ca \\


\section*{Introduction}

%Edited outline with Lizzie Nov 29 2023

\begin{enumerate}
%1-2 paragraphs
\item Climate change --- phenology --- variability
\begin{enumerate}
\item Paragraph 1
\begin{enumerate}
\item Climate change shifting phenology
\item Give example of range of climate change, or the mean etc
\item High variability
\item Some of the variability --- regional warming could explain
\end{enumerate}

\item Paragraph 2
\begin{enumerate}
\item But not enough --- species variable
\item Why care? --- forecasting and ecosystem services
\end{enumerate}
\end{enumerate}

\item Why spp may vary
\begin{enumerate}
\item Within a community several weeks for diff spp
\item Introduce temporal niche
\begin{enumerate}
\item resource competition
\item understory trees
\end{enumerate}
\end{enumerate}

\item Does population matter too?
\begin{enumerate}
\item Phenology differs in different places
\item Population differ --- local adaptation to environment and spp in community --- truly different phenology
\item Same underlying phenology but different climate --- high interannual variability
\end{enumerate}

\item Cues --- phenology
\begin{enumerate}
\item Even doy varies --- animals and plants have identical cue systems --- cite Bonamour
\item Universal cues --- photo and temp --- consistent in controlled environments
\item photo by latitude
\end{enumerate}

\item What do we need?
\begin{enumerate}
\item Spp variability
\item Population variability
\item Remove interannual variability by identifying cues
\item Given that cues/species have evolved over long timescales --- consider phylogeny
\end{enumerate}

\item Spring budburst --- good study system
\begin{enumerate}
\item Three primary cues --- winter and spring temps and photoperiod
\item Temporal niche by cues
\item Phenotypic differences --- functional groups and growth strategies --- spp can vary phenology and optimize their temporal niche.
\end{enumerate}

\item Here we:
\begin{enumerate}
\item Combined results from two growth chamber studies of woody plant phenological cues
\item Data from four populations, from eastern to western North America and a range of 4-6$^{\circ}$ latitude
\item Allows us to detect general trends in how bb of N Am. deciduous forest communities respond to forcing, chilling, photoperiod 
\item But also community specific responses---detect differences between Western and Eastern forest communities, and at different latitudes
\item And trends across different functional groups, exploring differences between the shrubs that dominate the forest understory and tree species.
\end{enumerate}
\end{enumerate}

%\item Climate change --- phenology --- variability
%emwDec12: Not sure we need so much 'Across the tree of life. In synthesizing across diverse species and habitats' ... etc -- This all reads like you will focus big on phylogenetics and diverse organisms ... You also introduce here the concept of phenology as a trait (debatable but certainly too much for an opening paragraph) and regional differences ... be careful with how many specifics you give that readers don't really need. 
Climate change is altering the timing of species life history events---phenology---with average advances of 2.6-2.8 days per decade \citep{Parmesan2007, Thackeray2016, Cohen2018}. Phenological events and their responses to climate change, however, are highly variable. Many events, such as leafout, span a period of weeks in most communities and are shifting in response to cliamte change at different rates \citep{Parmesan2007, Fitter2002, Menzel2006, Yu2010, Fridley2012}. \\

%emwDec12: Again, so much going on here! Cues, population variation -- make life easier on the reader and set these up more slowly. 
% Some of this variation is likely driven by . For many species, we have a limited understanding of their phenological cues and their relative importance across populations. But identifying the drivers of this important life history trait is necessary to predict future changes in phenology, and ultimately, its impacts on community dynamics and ecosystem services, like carbon cycles and pollination \citep{Gotelli1996,Cleland2007,Richardson2009}.\\%,Richardson2013,Keenan2014}. 
Understanding and explaining this variability is an important goal that remains extremely challenging. Some degree of this variability is likely due to differences in climate change itself across space---as some areas have warmed faster than others and may generate larger phenological shifts \citep{IPCC2018}. Cliamte change alone, however, explains a limited amount of the total variation. In contrast, substantial variation is due to species-level differences in phenology \citep{Vitasse2009, Wolkovich2014, Zohner2014, Vitasse2018}, but we still have a limited understanding of how they compares to other potential sources of variation, including those at the population-level % and climate.%dlDec13 I think you mean local climate, but seems confuisng given we disucss climate change above.
Understanding the role and scale of species-level variation, however is necessary to predict future changes in phenology, and ultimately, its impacts on community dynamics and ecosystem services, like carbon cycles and pollination \citep{Gotelli1996,Cleland2007,Richardson2009}.\\
\\
%emwDec12: This needs some work to build up to the concept of temporal niches... I added a new opening sentence and from here we need to better guide the reader through: okay, they vary, why? Well, because ... and then after I would define or introduce the term 'temporal niche'
Different species often have unique phenologies---even within the same location and climate conditions. In varying the timing of their phenological events within a community, species can limit the overlap in their resource use and the extent of competition they experience. For example, in forest communities, understory species often budburst earlier than canopy trees, when light and soil nutrients are more available. Varying the timing of phenological events within a community allows species to differ in their resource use and responses to environmental conditions that change across the growing season, ultimately filling different temporal niche within a season \citep{Gotelli1996}. \\

% dlDec13: old text 
% In varying the timing of their phenological events within a community, species can fill different temporal niche within a season \citep{Gotelli1996}. This can limit the overlap in species resource use and the extent of competition, promoting species coexistence and diversity. For example, in forest communities, understory species often budburst earlier than canopy trees, when light and soil nutrients are more available. This may further select for differences in species growth strategies and promote species differences in traits, like phenology. \\

%emwDec12: I am not sure we want to say this: Differences in species temporal niche can also arise from varying environmental conditions. ... it's rather nuanced and even tripped me up in thinking whether it was true. I would open instead with something about species variation being important, but lots of evidence that populations may differ too ...And again, walk though this more slowly and easily for the reader. Start with the reality that phenology varies a LOT across location, given an example of birds across an elevational gradient or something. Then say we don't always know how much of that is plasticity or local adaptation, but it were local adapation it would mean population level difference that could drive important phenological variation. 

While speices temporal niche differences allow more species to coexistence in a community, there is considerable evidence that they are also shaped by population differences as well. Phenology can be highly variable across populations and select for locally optimum trait phenotypes across populations. This has been shown across many ecosystems, including for bird breeding phenology in montane meadows in Sierra Nevada, for which breeding occurred 12 days earlier in low elevation communities \citep{Saracco2022}. How much of this variability, however, is due to local adaptation or plasticity is still unclear. In studying species phenologies across populations, we would expect the presenece of strong population-level differences to indicate that local adapation is an important driver of phenologicaly variation. \\


% Within a population, we expect traits like phenology to undergo local adaptation to environmental factors. While under constant conditions species express the same underlying phenology, climate cues can be highly variable across years and therefore select for locally optimum trait phenotypes across a species distribution.\\
%emwDec12: "local adaptation to both environmental factors, in addition to selection from biotic interactions, like competition" -- does it matter? Just introducing the concept of local adaptation seems enough and I would focus on climate as there's not much evidence for the biotic (again, introduce what you need to and not so much more) ... 

%emwDec12: Seems more natural to open this with the reality that teasing out plasticity from local adaptation requires knowing the cue systems ... 
While the potential for local adaptation can be drawn from differences across populations, teasing apart the effects of plasticity also requires knowledge of species cue systems. Both animals and plants often have very similar cue systems \citep{Bonamour2019}. Most species respond to variation in temperature and photoperiod cues, with consistent phenological responses occurring under controlled environments. Across species distributions, we would expect to find  biogeographic gradients in phenology in response to similar gradients in cues. Both photoperiod and temperatures vary across latitudinal gradients, possibly leading to similar gradients in phenology.  \\


%emwDec12: You have jumped to forests in the topic sentence without introducing them ... but otherwise, I like the sentence. 
%emwDec12: as shaped by their phenotypic variation and local biotic interactions. -- do we do this in the paper? I don't think so, so we either need to rephrase or cut. 
%emwDec12: As I mentioned, avoid using lots of new terms -- you introduce species distribution and biogeography when I think you're mostly talking about population level variation? If you want to switch terms you need to introduce the connection to readers (something like, 'these population-level differences could produce important biogeographic trends' ... but I don't actually think you need all these new terms. 
To predict how communities will respond to continued climate change requires a holistic approach that accounts for the multiple drivers of phenological variability. For a given community, we must account for differences across species as shaped thier temporal niche. But this cannot be done in isolation of population-level variation. In conducting experiments in controlled environments, we can remove the relative effects of interannual climate variability and identify speices primary cues. The use of recent phylogenetic methods also provides a means to account for climate variability during the long evolutionary timescales over which communities assembled \citep{Davies2013}. \\

Spring budburst offers an excellent system to test for species-level and spatial patterns in phenology and cue responses. Budburst of temperate woody plants is known to respond to temperature cues in both the winter and spring, also referred to as chilling and forcing respectively, as well as daylength \citep{Chuine2010,Polgar2011,Cooke2012,Basler2014,Laube2014}. These three cues interact to shape the start of spring growth, with variation in the relative importance of individual cues across species. Phenotypic differences between species --- such as functional groups and varying growth strategies --- further promotes phenological differences and ultimately optimize species temporal niche within a community.\\

Here we combined results from two growth chamber studies of woody species budburst cues. We used data from four populations, from eastern to western North America, with pairs of populations on each coast spanning 4-6$^{\circ}$ latitude respectively. Using a phylogenetic approach allowed us to detect general trends in budburst cue responses in North American deciduous forest communities. We also explored community specific responses to detect differences between western and eastern forest communities, and across latitudes. By including diverse assemblages of species, we tested for differences between functional groups, comparing the dominant shrub and tree species that characterize our forest understories and canopy.\\

\bibliographystyle{bibliography/bibstyles/amnat}% 
\bibliography{bibliography/phenoBCBib.bib}
\end{document}