\documentclass{article}

% required 
\usepackage[hyphens]{url} % this wraps my URL versus letting it spill across the page, a bad habit LaTeX has

\usepackage{Sweave}
\usepackage{graphicx}
\usepackage{natbib}
\usepackage{amsmath}
\usepackage{textcomp}%amoung other things, it allows degrees C to be added
\usepackage{float}
\usepackage[utf8]{inputenc} % allow funny letters in citaions 
\usepackage[nottoc]{tocbibind} %should add Refences to the table of contents?
\usepackage{amsmath} % making nice equations 
\usepackage{listings} % add in stan code
\usepackage{xcolor}
\usepackage{capt-of}%alows me to set a caption for code in appendix 
\usepackage[export]{adjustbox} % adding a box around a map
\usepackage{lineno}
\linenumbers
% recommended! Uncomment the below line and change the path for your computer!
% \SweaveOpts{prefix.string=/Users/Lizzie/Documents/git/teaching/demoSweave/Fig.s/demoFig, eps=FALSE} 
%put your Fig.s in one place! Also, note that here 'Fig.s' is the folder and 'demoFig' is what each 
% Fig. produced will be titled plus its number or label (e.g., demoFig-nqpbetter.pdf')
% make your captioning look better
\usepackage[small]{caption}

\usepackage{xr-hyper} %refer to Fig.s in another document
\usepackage{hyperref}

\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{0pt}
\setlength{\belowcaptionskip}{10pt}

% optional: muck with spacing
\topmargin -1.5cm        
\oddsidemargin 0.5cm   
\evensidemargin 0.5cm  % same as oddsidemargin but for left-hand pages
\textwidth 15.59cm
\textheight 21.94cm 
% \renewcommand{\baselinestretch}{1.5} % 1.5 lines between lines
\parindent 0pt		  % sets leading space for paragraphs
% optional: cute, fancy headers
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead[LO]{Draft summer 2023}
\fancyhead[RO]{Temporal Ecology Lab}
% more optionals! %

\graphicspath{ {./figures/} }% tell latex where to find photos 
\externaldocument[supp-]{phenoNAmPhylo_SM}
\begin{document}
\renewcommand{\bibname}{References}%names reference list 

\SweaveOpts{concordance=TRUE} % For RStudio hiccups


\title{Evolutionary history---more than phenological cues---explain temporal assembly of woody plant communities}
\date{\today}
\author{Deirdre Loughnan$^1$ and E M Wolkovich$^1$}
\maketitle 

$^1$ Department of Forest and Conservation, Faculty of Forestry, University of British Columbia, 2424 Main Mall
Vancouver, BC, Canada, V6T 1Z4. \\

Corresponding Author: Deirdre Loughnan, deirdre.loughnan@ubc.ca \\


\section*{Introduction}
<<label=runcode1,  echo=FALSE>>=

source("..//rcode/phenologyMsValues.R")
@

%emwOct25 --I also wonder if you can JUMP in -- have a starting sentence about big impacts on phenology, but not uniform. CC impacts is so common that I think starting with something narrower for this paper would be good. Also, I would not jump to forest communities or budburst so soon -- stay broad (unless you want to submit to a narrow forest-focused journal) -- you don't need them. 
%emw17Nov -- you have a lot going on here in two sentences: are you trying to say that because of uneven warming effects are non-uniform? It reads closest to that, but that seems a very specific way to start a paper where you suggest other things matter. 
\begin{enumerate}
\item Climate change = altering the timing of life history events across the tree of life.
\begin{enumerate}
\item But see high variability in phenological shifts between species and habitats %\citep{Fitter2002,Menzel2006,Yu2010,Fridley2012}. 
%\item Species that vary in phenology within a season can fill different  temporal niche \citep{Gotelli1996}---
\item E.g. plants understory species often budburst earlier than canopy trees---while within a habitat individual bird species can vary their reproduction by several months % \citep{SanzAguilar2015}
\item Understanding relative importance of environmental versus species traits to phenology = needed to understand and predict future impacts of climate change and ecosystem services---carbon sequestration, species interactions
\end{enumerate}

%emw17Nov --... I think the previous paragraph probably needs to set up more of a mystery or problem: variability. And then you can either (1) close on one reason being uneven warming, but say that's not it alone?  And Here you aim to introduce other sources of variation that occur at species and population levels. Or (2) end on variability and how important predicting it is (last sentence here) and make this next paragraph an overview of potential drivers: uneven warming, geography, population and species diffs. Either way you need a better transition to niches. 
%DL18Nov: trying option 2

\item While phenological variation often attributed to species-level differences---considerable influence of geographic variation in environmental cues as well %\citep{Vitasse2009,Wolkovich2014,Zohner2014,Vitasse2018}. 
\begin{enumerate}
\item Phenotypic differences---physiological traits and growth strategies---allow species to vary timing of phenological events and optimize their temporal niche. 
% \item Predict closely related species exhibit similar traits and be more likely to have similar phenological cues
\item But within species could still get local adaptation = population differences due to gradients in environmental cues%--- eg. daylength and temperature
\item Declines in both temperature and photoperiod with latitude have the potential to create similar gradients in cues across populations.
\item But still unclear what the relative effects of population versus species-level variation in shaping phenology and communities overall.
\end{enumerate}

\item Spring budburst offers an excellent system to study the drivers of phenological events.
\begin{enumerate}
\item Decades of work = under controlled environments budburst cues are consistent.
\item Woody plants = cool winter and warm spring temperature cues, and daylength %\citep{Chuine2010,Polgar2011,Cooke2012,Basler2014,Laube2014}.
\item Cues can also have interactive effects---provide compensatory mechanisms if individual cues are insufficient % \citep{Heide1993,Chuine2000,Caffarra2011,Flynn2018}
\item While in nature phenology is highly variable---its consistency in experimental settings provides unique opportunity to test for generalizable trends across cues and communities.
\end{enumerate}

\item  Differences in cues shape forests adaptive potential, altering the competitive landscape across the growing season = determining species diversity and persistence.
\begin{enumerate}
\item Understanding these mechanisms is critical as global warming is disproportionately affecting high latitude communities
\item Warmer temperatures could = lead to faster accumulation of temperature cues and greater advances in phenology %\citep{Guy2014}. 
\item But, species with strong photoperiod = reduced fitness---ability to adapt constrained by constant photoperiod cues %\citep{Way2015}. 
\item Identifying the ways in which climate change will reshape forest communities is needed to predicting the changes to forest communities likely to arise across species ranges %\citep{Willis2010,Wolkovich2013}. 
% \item Locally, could create novel niche space within a season---creating novel communities across species ranges \citep{Willis2010,Wolkovich2013}. 
%
% \item Together cues and species phenotypes shape species temporal niche and coexistence across space---but for most phenological events we have a limited understanding of how traits and cues interact.
% \item Confounding these geographic gradients = uneven effects of climate change---greatest changes in temp = high latitiude \citep{IPCC2018} %DLNov21 I might cut this from intro and come back to it in discussion in the context of why this matters
\end{enumerate}
%more closely related species should = more similar growth strategies


%emw17Nov -- the comparison of space versus phylogeny is confusing to me, phylogeny can help explain species-level differences through testing for trends with shared evolutionary history, so it feels weird to focus on the space vs. phylogeny comparison. I think we need to better integrate this with a focus on *species* level differences and then get the reader to a point where they understand your work lets you look at species-level differences, including due to phylogeny and population (spatial) level differences as a whole package. You probably need multiple paragraphs to do this ...
\item While climate change effects on temperature cues are recent, we must account for the longer timescales over which communities assembled%\citep{Davies2013}
---historic conditions shaped traits, like phenology, that we observe today.
\begin{enumerate}
\item More closely related species may express similar phenotypes---including their phenological traits---than more distantly related species.
\item But different species have experienced different historic cues, possibly driving variation in phenotypes and cue responses. 
% \item Few studies have accounted for the effects of evolutionary time on phenology using multiple populations of the same forest communities. 
\item To better predict responses and community assembly w/ climate change = must account for species history and the present cues driving budburst. \\
\end{enumerate}

\item In this study we:
\begin{enumerate}
\item Combined results from two growth chamber studies of woody plant phenological cues
\item Data from four populations, from eastern to western North America and a range of 4-6$^{\circ}$ latitude
\item Allows us to detect general trends in how bb of N Am. deciduous forest communities respond to forcing, chilling, photoperiod 
\item But also community specific responses---detect differences between Western and Eastern forest communities, and at different latitudes
\item And trends across different functional groups, exploring differences between the shrubs that dominate the forest understory and tree species.
\end{enumerate}
\end{enumerate}

% \bibliographystyle{bibliography/bibstyles/amnat.bst}%
% \bibliography{bibliography/phenoBCBib.bib}


\end{document}