\documentclass{article}

% required 
\usepackage[hyphens]{url} % this wraps my URL versus letting it spill across the page, a bad habit LaTeX has

\usepackage{Sweave}
\usepackage{graphicx}
\usepackage{natbib}
\usepackage{amsmath}
\usepackage{textcomp}%amoung other things, it allows degrees C to be added
\usepackage{float}
\usepackage[utf8]{inputenc} % allow funny letters in citaions 
\usepackage[nottoc]{tocbibind} %should add Refences to the table of contents?
\usepackage{amsmath} % making nice equations 
\usepackage{listings} % add in stan code
\usepackage{xcolor}
\usepackage{capt-of}%alows me to set a caption for code in appendix 
\usepackage[export]{adjustbox} % adding a box around a map
\usepackage{lineno}
\linenumbers
% recommended! Uncomment the below line and change the path for your computer!
% \SweaveOpts{prefix.string=/Users/Lizzie/Documents/git/teaching/demoSweave/Fig.s/demoFig, eps=FALSE} 
%put your Fig.s in one place! Also, note that here 'Fig.s' is the folder and 'demoFig' is what each 
% Fig. produced will be titled plus its number or label (e.g., demoFig-nqpbetter.pdf')
% make your captioning look better
\usepackage[small]{caption}

\usepackage{xr-hyper} %refer to Fig.s in another document
\usepackage{hyperref}

\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{0pt}
\setlength{\belowcaptionskip}{10pt}

% optional: muck with spacing
\topmargin -1.5cm        
\oddsidemargin 0.5cm   
\evensidemargin 0.5cm  % same as oddsidemargin but for left-hand pages
\textwidth 15.59cm
\textheight 21.94cm 
% \renewcommand{\baselinestretch}{1.5} % 1.5 lines between lines
\parindent 0pt		  % sets leading space for paragraphs
% optional: cute, fancy headers
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead[LO]{Draft early 2022}
\fancyhead[RO]{Temporal Ecology Lab}
% more optionals! %

\graphicspath{ {./figures/} }% tell latex where to find photos 
%\externaldocument[supp-]{Synchrony_Manuscript_supp}
\begin{document}
\renewcommand{\bibname}{References}%names reference list 

\SweaveOpts{concordance=TRUE} % For RStudio hiccups


\title{Cue responses in woody plants of North America}
\date{\today}
\author{Deirdre Loughnan$^1$ and E M Wolkovich$^1$}
\maketitle 

$^1$ Department of Forest and Conservation, Faculty of Forestry, University of British Columbia, 2424 Main Mall
Vancouver, BC, Canada, V6T 1Z4. \\

Corresponding Author: Deirdre Loughnan, deirdre.loughnan@ubc.ca \\


\section{Research questions:}

\begin{enumerate}
\item How do species in deciduous forests across North America respond to varying chilling, forcing, and photoperiod cues?
\item Do we see similar trends when we compare species eastern deciduous forests to western deciduous forests communities? 
\item How do shrub species differ from tree species in their cue use?
\end{enumerate}

\section{Results}

\begin{enumerate}
\item General Survival and germination success

\begin{enumerate}
\item 2496 samples went into chilling
\item 2458 survived the experiment
\item 1.52\% mortality
\item 9.5\% of the remaining samples did not budburst at all
\item 18.42\% did not have terminal budburst, most of these were vac mem, followed by rubpar and acegla. 
\end{enumerate}

\item Our model found...
\begin {enumerate}
\item The root trait was X and lambda was X - meaning...
\item While all cues did lead to the advance in budburst date, there were strong interactions between cues and between cues and sites.
\item Strong delaying interaction between forcing and chilling 
\item Strong delaying interaction between forcing and the two eastern sites
\item Strong delaying interaction between chilling and the two eastern sites
\item moderate advancing interaction between photoperiod and our eastern sites
\end {enumerate}
\end{enumerate}

\section{Tables and figures}

<<label= tab4Site, echo=FALSE, results=tex >>=
require(rstan)
require(xtable)

load("..//output/final/bb_4sites_phylo.Rda")

sum <- summary(mdl.4phylo)$summary 

col4fig <- c("mean","sd","25%","50%","75%","n_eff","Rhat")
col4table <- c("mean","sd","2.5%","50%","97.5%","n_eff","Rhat")

mu_params_4 <- c(
                #"a_z","lam_interceptsa",
                "mu_b_warm", "mu_b_photo", "mu_b_chill1", "b_site2",
                "b_site3", "b_site4", "mu_b_inter_wp",
                "mu_b_inter_wc1","mu_b_inter_pc1", "mu_b_inter_ws2",
                "mu_b_inter_ps2","mu_b_inter_s2c1", "mu_b_inter_ws3",
                "mu_b_inter_ps3", "mu_b_inter_s3c1", "mu_b_inter_ws4",
                "mu_b_inter_ps4","mu_b_inter_s4c1")

meanz4 <- sum[mu_params_4, col4fig]

rownames(meanz4) = c( #"Root trait intercept","Lambda",
                      "Forcing",
                      "Photoperiod",
                      "Chilling",
                      "Manning Park",
                       "Harvard Forest",
                       "St. Hippolyte",
                      "Forcing x photoperiod",
                      "Forcing x chilling",
                      "Photoperiod x chilling",
                      "Forcing x Manning Park",
                      "Photoperiod x Manning Park",
                      "Chilling x Manning Park",
                      "Forcing x Harvard Forest",
                      "Photoperiod x Harvard Forest",
                      "Chilling x Harvard Forest",
                      "Forcing x St. Hippolyte",
                      "Photoperiod x St. Hippolyte",
                      "Chilling x St. Hippolyte"            
)

meanz4.table <- sum[mu_params_4, col4table]
row.names(meanz4.table) <- row.names(meanz4)

fourSite <- xtable(meanz4.table, caption="Summary output from a phylogenetic mixed-effect model in which species are partially pooled and phylogeny is included on the intercept. The model includes photoperiod, forcing, and site as dummy variables, while the chilling effect is included as continuous chill portions.")
print(fourSite,include.rownames=TRUE, caption.placement="top", hline.after=c(-1,0))

@

\begin{figure}[h!]
    \centering
     \includegraphics[width=\textwidth]{..//figures/changes_pheno_4sites.pdf} 
    \caption{Estimated responses in budburst date across all bud types. }
    \label{fig:muplot}
\end{figure}

\begin{figure}[h!]
    \centering
     \includegraphics[width=\textwidth]{..//figures/cueEW.pdf} 
    \caption{Interaction plots for the western transect. a) The interaction between chill portions and forcing, b) the interaction between photoperiod and chilling, and c) the relationship between forcing and site}
    \label{fig:cues}
\end{figure}

\begin{figure}[h!]
    \centering
     \includegraphics[width=\textwidth]{..//figures/cueST.pdf} 
    \caption{Interaction plots for the western transect. a) The interaction between chill portions and forcing, b) the interaction between photoperiod and chilling, and c) the relationship between forcing and site}
    \label{fig:cues}
\end{figure}

\begin{figure}[h!]
    \centering
     \includegraphics[width=\textwidth]{..//figures/cueSp.pdf} 
    \caption{Interaction plots for the western transect. a) The interaction between chill portions and forcing, b) the interaction between photoperiod and chilling, and c) the relationship between forcing and site}
    \label{fig:cues}
\end{figure}

\begin{figure}[h!]
    \centering
     \includegraphics[width=\textwidth]{..//figures/cueCompare.pdf} 
    \caption{Interaction plots for the western transect. a) The interaction between chill portions and forcing, b) the interaction between photoperiod and chilling, and c) the relationship between forcing and site}
    \label{fig:cues}
\end{figure}

\end{document}